### ISSUE TITLE
No preview available 

### ISSUE THREAD

**Issue by GALSEN22** [stackblitz-labs/bolt.diy#400]
### Describe the bug

Hi, 

I have an issue, 
When i start a project, after a certain time i don't have anymore the preview and the only message i'm seing is no preview available

### Link to the Bolt URL that caused the error

localhost:

### Steps to reproduce

I've just launched new instructions for my project

### Expected behavior

Show the preview

### Screen Recording / Screenshot

![Capture d'écran 2024-11-24 132301](https://github.com/user-attachments/assets/d4ba84a5-2485-4567-b9c5-cf688a77b20f)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by sallespro** [comment]
preview is working for me as well.
i ran the development setup with `docker compose --profile development up` asked ollama to create a boilerplate app, it did work well with `qwen2.5-coder-extra-ctx:7b`  created extending token limits.

the preview address is `https://k03e2io1v3fx9wvj0vr8qd5q58o56n-fkdo--5173--d3acb9e1.local-corp.webcontainer-api.io`
i wonder this domain can not be reached...or is incorrect.

**Comment by pr0j3c7t0dd** [comment]
I'm having the same issue.  The page is created, but there's nothing when I run `npx serve --single` (simple html page)

**Comment by pcherkashin** [comment]
Now preview available
I Installed Bolt with Docker on Debian server, was trying to create a login page. Had a code, but now preview. Log for this generation:
❯ cat /home/.npm/_logs/2024-11-27T18_02_13_390Z-debug-0.log
0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@10.2.3
2 info using node@v18.20.3
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 4ms
6 timing config:load:builtin Completed in 4ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/project/.npmrc Completed in 5ms
10 timing config:load:project Completed in 37ms
11 timing config:load:file:/home/.npmrc Completed in 18ms
12 timing config:load:user Completed in 18ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 5ms
14 timing config:load:global Completed in 5ms
15 timing config:load:flatten Completed in 3ms
16 timing config:load:setEnvs Completed in 0ms
17 timing config:load Completed in 74ms
18 timing npm:load:configload Completed in 74ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 1ms
21 verbose title npm run dev
22 verbose argv "run" "dev"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:/home/.npm/_logs/2024-11-27T18_02_13_390Z-
26 verbose logfile /home/.npm/_logs/2024-11-27T18_02_13_390Z-debug-0.log
27 timing npm:load:logFile Completed in 13ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 93ms
31 timing command:run Completed in 6ms
32 verbose stack ENOENT: no such file or directory, open '/home/project/package.json'
33 verbose cwd /home/project
34 verbose Linux 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
35 verbose node v18.20.3
36 verbose npm  v10.2.3
37 error code ENOENT
38 error syscall open
39 error path /home/project/package.json
40 error errno -2
41 error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/home/project/package.json'
42 error enoent This is related to npm not being able to find a file.
42 error enoent
43 verbose exit -2
44 timing npm Completed in 156ms
45 verbose code -2
46 error A complete log of this run can be found in: /home/.npm/_logs/2024-11-27T18_02_13_390Z-debug-0.log

In project folder I have only /src and components.json and no package.json file

**Comment by dustinwloring1988** [comment]
it might just not have packages i would love to see the code and terminal view, maybe try something simple like asking it to make a html, css and js website.

**Comment by kismonguz** [comment]
I tested again. After started the project selected the quen2.5-coder7b (with extended parameter numbers), and simply clicked the "Build a todo app in React using Tailwind" link. 
It looks like the now preview error related to the incorrect code generation of the model. I tested with Chatgpt 4o an dquen2.5-coder-14b and they worked.

**Comment by dustinwloring1988** [comment]
@kismonguz please list you environment. ( OS, how you are running this fork, how you are running ollama, any and all commands you ran after cloning it )

**Comment by kismonguz** [comment]
> @kismonguz please list you environment. ( OS, how you are running this fork, how you are running ollama, any and all commands you ran after cloning it )

Here is some details about my test. I currently did it again. I made 2 test with the 7b and 14b models. Details below.

**Environment**

- os: Windows 11 Pro for Workstations 23H2 build: 22631.4541
- Memory: 16GB
- CPU: Ryzen5 2600
- GPU: GeForce RTX 4070 (12GB RAM)
- chrome: 131.0.6778.86
- node: v20.11.1
- ollama: ollama version is 0.4.7
- bolt.new-any-llm current hash: 0d49c7402b74e38af66a1edcba27d88739b46bef
I ran it natively on windows, didn't use docker.

**Test 1**
model: quen2.5-extra:7b 
made from qwen2.5-coder:7b based on this article: https://coleam00.github.io/bolt.new-any-llm/#super-important-note-on-running-ollama-models
```
FROM qwen2.5-coder:7b
PARAMETER num_ctx 32768
```
**What I did:** 
- Started the program with "pnpm run dev" command
- Selected the model I mentioned
- Clicked the "Build a todo app in React using Tailwind" button.

**Results:**
![test1_result](https://github.com/user-attachments/assets/91ba2120-0b6b-4e3b-a3aa-6823b17eb50d)
[test1_source.zip](https://github.com/user-attachments/files/17985686/test1_source.zip)
[test1_chat.json](https://github.com/user-attachments/files/17985687/test1_chat.json)


**Test2**
model: quen2.5-extra:14b 
made from qwen2.5-coder:14b based on this article: https://coleam00.github.io/bolt.new-any-llm/#super-important-note-on-running-ollama-models
```
FROM qwen2.5-coder:14b
PARAMETER num_ctx 32768
```
**What I did:** 
- Started the program with "pnpm run dev" command
- Selected the model I mentioned
- Clicked the "Build a todo app in React using Tailwind" button.

**Resulst:**
The result totally different. At the first step of the generation, the install process stucked, because the command is not silent. I manually proceed it with the following answers(I think the AI would chose this options):
Select a framework: › React
Select a variant: › TypeScript + SWC
If I'm not fast enought, I have to manually run the "npm install command" and the "npm run dev" command, but in the end the todo app works.

![test2_stuck](https://github.com/user-attachments/assets/bb55b0a6-14b9-4d41-ad7b-d0f9b93c3540)
![test2_bolt_result](https://github.com/user-attachments/assets/50d17b6b-8c8a-43dc-9c98-cfb22377af1e)
[test2_chat.json](https://github.com/user-attachments/files/17985702/test2_chat.json)
[test2_source.zip](https://github.com/user-attachments/files/17985703/test2_source.zip)


**Final thoughts:**
Unfortunately I'm a Vue guy, so I don't know exactly the propper React starter setup, but I think, there is some problem with the generated code.

Hope it helps.

**Comment by dustinwloring1988** [comment]
can you please try multiply browser with and with private mode

**Comment by kismonguz** [comment]
I tried. Here is my results:
- Chrome private: I got same result: empty preview
- Edge(131.0.2903.70) normal:  I got same result: empty preview
- Edge(131.0.2903.70) private:  I got same result: empty preview
- Firefox(133.0) normal:  I got same result: empty preview
- Firefox(133.0) private: There is a problem with firefox private mode
![bolt_firefox_private](https://github.com/user-attachments/assets/ef085fa9-3fac-42e3-98b4-b91768171002)

**Comment by dustinwloring1988** [comment]
@kismonguz thanks for the testing this will help. 

Your not using any addons to the browsers are you? 

You didn't change your privacy setting in your OS or browsers did you?

Can you do a discord conversation so you can screen share and try a few things, I would love to tackle this bug?

Looks like we are getting somewhere with the calls now being complete at least.

**Comment by kismonguz** [comment]
In the chrome I use some plugins but in incognito mode, or in the other browsers I do not use anything.
I think my OS privacy settings mostly the default.

I'm OK with a discord conversation. Is there any public server?

**Comment by dustinwloring1988** [comment]
Here i made one real fast: https://discord.gg/adXUP4hw

**Comment by kismonguz** [comment]
tiny update: one step forward two steps backward

I switched from ollama to LM Studio nothing else changed. It increased the overall performance using bigger models and no I can access some tweak options inside LM Studio.

But in the other hand, in the bolt app, I constantly get an error when executing "npm run dev" command. And it starts consuming all the memory of the universe (but stopped after reach the limit of my pc). I think it is a different kind of error than the original one.
```
❯ npm run dev

> todo-app@0.0.0 dev
> vite

  VITE v4.5.5  ready in 2430 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
Error: module is not defined
    at file:///home/project/postcss.config.js
    at async ModuleLoader.import (https://k03e2io1v3fx9wvj0vr8qd5q58o56n-fkdo.w-corp-staticblitz.com/builtins.ddb8d84d.js:154:2688)
    at async importDefault (file:///home/project/node_modules/vite/dist/node/chunks/dep-b2890f90.js:36608:18)
    at async Object.search (file:///home/project/node_modules/vite/dist/node/chunks/dep-b2890f90.js:29044:38) {
  name: 'Failed to load PostCSS config'
}

Node.js v18.20.3

~/project 3s
❯ fatal error: too many writes on closed pipe

goroutine 6 [running]:
runtime.throw({0x9deaa, 0x1e})
        runtime/panic.go:1047 +0x3 fp=0x83aed8 sp=0x83aeb0 pc=0x12250003
os.sigpipe()
        runtime/os_js.go:144 +0x2 fp=0x83aef0 sp=0x83aed8 pc=0x13b70002
os.epipecheck(...)
        os/file_unix.go:224
os.(*File).Write(0x80c020, {0x86c240, 0x2d, 0x40})
        os/file.go:183 +0x2d fp=0x83af78 sp=0x83aef0 pc=0x1607002d
main.runService.func1()
        github.com/evanw/esbuild/cmd/esbuild/service.go:99 +0x7 fp=0x83afe0 sp=0x83af78 pc=0x1f630007
runtime.goexit()
        runtime/asm_wasm.s:399 +0x1 fp=0x83afe8 sp=0x83afe0 pc=0x14070001
created by main.runService
        github.com/evanw/esbuild/cmd/esbuild/service.go:97 +0x1e

goroutine 1 [chan receive]:
runtime.gopark(0xb66b0, 0x834178, 0xe, 0x17, 0x2)
        runtime/proc.go:381 +0x28 fp=0x897bc8 sp=0x897ba0 pc=0x124c0028
runtime.chanrecv(0x834120, 0x0, 0x1)
        runtime/chan.go:583 +0x7f fp=0x897c50 sp=0x897bc8 pc=0x106d007f
runtime.chanrecv1(0x834120, 0x0)
        runtime/chan.go:442 +0x2 fp=0x897c78 sp=0x897c50 pc=0x106b0002
github.com/evanw/esbuild/internal/helpers.(*ThreadSafeWaitGroup).Wait(...)
        github.com/evanw/esbuild/internal/helpers/waitgroup.go:36
main.runService.func2()
        github.com/evanw/esbuild/cmd/esbuild/service.go:114 +0x8 fp=0x897c98 sp=0x897c78 pc=0x1f620008
main.runService(0x1)
        github.com/evanw/esbuild/cmd/esbuild/service.go:160 +0x5c fp=0x897de0 sp=0x897c98 pc=0x1f60005c
main.main()
        github.com/evanw/esbuild/cmd/esbuild/main.go:240 +0x9e fp=0x897f88 sp=0x897de0 pc=0x1f59009e
runtime.main()
        runtime/proc.go:250 +0x32 fp=0x897fe0 sp=0x897f88 pc=0x12460032
runtime.goexit()
        runtime/asm_wasm.s:399 +0x1 fp=0x897fe8 sp=0x897fe0 pc=0x14070001

goroutine 2 [force gc (idle)]:
runtime.gopark(0xb6848, 0x3c65d0, 0x11, 0x14, 0x1)
        runtime/proc.go:381 +0x28 fp=0x828fb8 sp=0x828f90 pc=0x124c0028
runtime.goparkunlock(...)
        runtime/proc.go:387
runtime.forcegchelper()
        runtime/proc.go:305 +0x1f fp=0x828fe0 sp=0x828fb8 pc=0x1249001f
runtime.goexit()
        runtime/asm_wasm.s:399 +0x1 fp=0x828fe8 sp=0x828fe0 pc=0x14070001
created by runtime.init.5
        runtime/proc.go:293 +0x2

goroutine 3 [GC sweep wait]:
runtime.gopark(0xb6848, 0x3c6960, 0xc, 0x14, 0x1)
        runtime/proc.go:381 +0x28 fp=0x829798 sp=0x829770 pc=0x124c0028
runtime.goparkunlock(...)
        runtime/proc.go:387
runtime.bgsweep(0x82e000)
        runtime/mgcsweep.go:278 +0xf fp=0x8297d0 sp=0x829798 pc=0x1179000f
runtime.gcenable.func1()
        runtime/mgc.go:178 +0x2 fp=0x8297e0 sp=0x8297d0 pc=0x110d0002
runtime.goexit()
        runtime/asm_wasm.s:399 +0x1 fp=0x8297e8 sp=0x8297e0 pc=0x14070001
created by runtime.gcenable
        runtime/mgc.go:178 +0x8

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xb6848, 0x3c6ba0, 0xd, 0x14, 0x2)
        runtime/proc.go:381 +0x28 fp=0x829f80 sp=0x829f58 pc=0x124c0028
runtime.goparkunlock(...)
        runtime/proc.go:387
runtime.(*scavengerState).park(0x3c6ba0)
        runtime/mgcscavenge.go:400 +0xd fp=0x829fa8 sp=0x829f80 pc=0x1160000d
runtime.bgscavenge(0x82e000)
        runtime/mgcscavenge.go:628 +0x4 fp=0x829fd0 sp=0x829fa8 pc=0x11650004
runtime.gcenable.func2()
        runtime/mgc.go:179 +0x2 fp=0x829fe0 sp=0x829fd0 pc=0x110c0002
runtime.goexit()
        runtime/asm_wasm.s:399 +0x1 fp=0x829fe8 sp=0x829fe0 pc=0x14070001
created by runtime.gcenable
        runtime/mgc.go:179 +0xe

goroutine 5 [finalizer wait]:
runtime.gopark(0xb66e8, 0x3e3850, 0x10, 0x14, 0x1)
        runtime/proc.go:381 +0x28 fp=0x828738 sp=0x828710 pc=0x124c0028
runtime.runfinq()
        runtime/mfinal.go:193 +0x1f fp=0x8287e0 sp=0x828738 pc=0x1104001f
runtime.goexit()
        runtime/asm_wasm.s:399 +0x1 fp=0x8287e8 sp=0x8287e0 pc=0x14070001
created by runtime.createfing
        runtime/mfinal.go:163 +0xd

goroutine 7 [waiting]:
runtime.gopark(0x0, 0x0, 0x0, 0x0, 0x1)
        runtime/proc.go:381 +0x28 fp=0x82af90 sp=0x82af68 pc=0x124c0028
runtime.handleEvent()
        runtime/lock_js.go:257 +0x1b fp=0x82afe0 sp=0x82af90 pc=0x10a3001b
runtime.goexit()
        runtime/asm_wasm.s:399 +0x1 fp=0x82afe8 sp=0x82afe0 pc=0x14070001
created by runtime.beforeIdle
        runtime/lock_js.go:207 +0x1a

goroutine 8 [sleep]:
runtime.gopark(0xb6888, 0x832190, 0x13, 0x13, 0x1)
        runtime/proc.go:381 +0x28 fp=0x82b768 sp=0x82b740 pc=0x124c0028
time.Sleep(0x3b9aca00)
        runtime/time.go:195 +0x1b fp=0x82b7a0 sp=0x82b768 pc=0x13d6001b
main.runService.func3()
        github.com/evanw/esbuild/cmd/esbuild/service.go:124 +0x5 fp=0x82b7e0 sp=0x82b7a0 pc=0x1f610005
runtime.goexit()
        runtime/asm_wasm.s:399 +0x1 fp=0x82b7e8 sp=0x82b7e0 pc=0x14070001
created by main.runService
        github.com/evanw/esbuild/cmd/esbuild/service.go:122 +0x41
```

**Comment by PsychoDude** [comment]
I'm having the exact same blank preview issue. It appears to be linked to tailwind as I am able to get a preview when asking for a react to-do app without tailwind.

**Comment by leex279** [comment]
@PsychoDude check your dev-tools (F12) for errors. if need more help, open a community ticket please


Closed for know: If still a problem, open a topic in community please to investigate deeper: https://thinktank.ottomator.ai/c/bolt-diy/bolt-diy-issues-and-troubleshooting/22
