### ISSUE TITLE
 Code Generation Fails to Create Files - File View Shows No Output

### ISSUE THREAD

**Issue by syberkitten** [stackblitz-labs/bolt.diy#517]
### Describe the bug

Been trying with various models, like sonnet-3-5. gemini pro,
I just get the files printed on the screen.
any ideas?

### Link to the Bolt URL that caused the error

my localhost

### Steps to reproduce

nothing is being executed in the Bolt Terminal,
no code file is being generated.

Everything appears in the chat only, no files are created.

### Expected behavior

should at least create one file, any file.

### Screen Recording / Screenshot

<img width="1472" alt="Screen Shot 2024-12-03 at 1 28 02" src="https://github.com/user-attachments/assets/2f75d12a-5f0c-4ee5-8bd3-f09c8b34e493">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by numosh** [comment]
Same here. Strange, first time running, its fine, then when running again, the coder seems untouch.

**Comment by dustinwloring1988** [comment]
@syberkitten @numosh 

can you please provide info about your environment:
    OS: [e.g. macOS, Windows, Linux]
    Browser: [e.g. Chrome, Safari, Firefox]
    Version: [e.g. 91.1]

**Comment by Fabrizio1990** [comment]
any news on this?
i am facing the same issue, i start the chat and the right side window is not opening, if i open it nothing is created and i only see the code in the chat.
PC: Macbook pro m1 16gb ram
OS: MacOS
Browser: Chrome
Model: qwen2.5-coder:3B (its only to test if it is running before buy some runpods credit and run the 32B)
Launch metod: Docker

**Comment by dustinwloring1988** [comment]
I have not had good luck with the small models, when using the bigger ones like qwen2.5-coder32B it works good though. Either try a bigger model or a frontier Model and see if that helps

**Comment by Fabrizio1990** [comment]
tried with qwen2.5-coder:7B and it worked, however running with docker don't show the site preview to me, also tested running without docker (installing packages) but seems that with this mode is not able to reach my ollama models and show some error on cursor console:
Error getting Ollama models: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11730:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.getOllamaModels [as getDynamicModels] (/Users/fabriziocoppolecchia/Desktop/Progetti/miei_personali/bolt-new/bolt.new-any-llm/app/utils/constants.ts:318:22)
    at async Promise.all (index 0)
    at Module.initializeModelList (/Users/fabriziocoppolecchia/Desktop/Progetti/miei_personali/bolt-new/bolt.new-any-llm/app/utils/constants.ts:389:9)
    at handleRequest (/Users/fabriziocoppolecchia/Desktop/Progetti/miei_personali/bolt-new/bolt.new-any-llm/app/entry.server.tsx:30:3)
    at handleDocumentRequest (/Users/fabriziocoppolecchia/Desktop/Progetti/miei_personali/bolt-new/bolt.new-any-llm/node_modules/.pnpm/@remix-run+server-runtime@2.15.0_typescript@5.7.2/node_modules/@remix-run/server-runtime/dist/server.js:340:12)
    at requestHandler (/Users/fabriziocoppolecchia/Desktop/Progetti/miei_personali/bolt-new/bolt.new-any-llm/node_modules/.pnpm/@remix-run+server-runtime@2.15.0_typescript@5.7.2/node_modules/@remix-run/server-runtime/dist/server.js:160:18)
    at /Users/fabriziocoppolecchia/Desktop/Progetti/miei_personali/bolt-new/bolt.new-any-llm/node_modules/.pnpm/@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_zyxju6yjkqxopc2lqyhhptpywm/node_modules/@remix-run/dev/dist/vite/cloudflare-proxy-plugin.js:70:25 {
  cause: Error: connect ECONNREFUSED ::1:11434
      at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
      at __node_internal_exceptionWithHostPort (node:internal/errors:671:12)
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:128:17) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 11434
  }
}


ollama is running and with docker is working (except for the preview) but without docker is not.. don't know why

**Comment by dustinwloring1988** [comment]
@Fabrizio1990 for the issue with the preview part not working you might need to try a bigger model try qwen2.5-coder32B as for the other issue we are still working on it.

**Comment by arno451** [comment]
Any news on this issue ?
I have the same sometimes it works, sometimes it doesn't.
OS: [ Windows ]
Browser: [ Brave ]
LLM : Ollama > qwen2.5-coder:7b
Localhost

nothing is being executed in the Bolt Terminal,
no code file is being generated.

**Comment by dustinwloring1988** [comment]
@arno451 please use a bigger model like it says to in the documentation, try 14b
