### ISSUE TITLE
Failed to execute 'postMessage' on 'Worker' ubuntu 22.04 

### ISSUE THREAD

**Issue by antongo10** [stackblitz-labs/bolt.diy#521]
### Describe the bug

Running on a Ubuntu 22.04 server.

1. Not detecting local ollama models, got it working at some point, but wanted to ask for any advice on how to setup the ollama and a reverse proxy so bolt can access?
```
Error getting Ollama models: TypeError: fetch failed
    at node:internal/deps/undici/undici:12618:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.getOllamaModels [as getDynamicModels] (/root/workspace/bolt.new-any-llm/app/utils/constants.ts:318:22)
    at async Promise.all (index 0)
    at Module.initializeModelList (/root/workspace/bolt.new-any-llm/app/utils/constants.ts:389:9)
    at handleRequest (/root/workspace/bolt.new-any-llm/app/entry.server.tsx:30:3)
    at handleDocumentRequest (/root/workspace/bolt.new-any-llm/node_modules/.pnpm/@remix-run+server-runtime@2.15.0_typescript@5.7.2/node_modules/@remix-run/server-runtime/dist/server.js:340:12)
    at requestHandler (/root/workspace/bolt.new-any-llm/node_modules/.pnpm/@remix-run+server-runtime@2.15.0_typescript@5.7.2/node_modules/@remix-run/server-runtime/dist/server.js:160:18)
    at /root/workspace/bolt.new-any-llm/node_modules/.pnpm/@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_zyxju6yjkqxopc2lqyhhptpywm/node_modules/@remix-run/dev/dist/vite/cloudflare-proxy-plugin.js:70:25 {
  cause: Error: connect ECONNREFUSED ::1:11434
      at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
      at __node_internal_exceptionWithHostPort (node:internal/errors:671:12)
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:128:17) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 11434
  }
}
```
2. cors issues, with an open port for bolt, tried setting up nginx with the following config for ollama:
```
server {
    listen 11435;
    server_name _;

    location / {
        proxy_pass http://127.0.0.1:11434;
        proxy_http_version 1.1;

        # Set headers for proxy requests
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Enable CORS
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Authorization, Accept' always;

        # Handle preflight requests
        if ($request_method = OPTIONS) {
            return 204;
        }
    }
}
```
3. issue in the screenshot - even with oAI model, Failed to execute 'postMessage'.

### Steps to reproduce

```shell
git clone https://github.com/coleam00/bolt.new-any-llm.git
npm run dockerbuild
docker build . --target bolt-ai-development
docker-compose --profile development up
 
or just 
pnpm run dev --host 0.0.0.0
``` 

### Expected behavior

1. ollama models detected. help with ubuntu setup
2. code agent running, currently fails.

### Screen Recording / Screenshot

<img width="1459" alt="Screenshot 2024-12-03 at 13 51 53" src="https://github.com/user-attachments/assets/9557c25d-0ff8-43e3-a8b8-e8c2f65301a1">

DEBUG Terminal Starting bolt terminal [0]
logger.ts:84 DEBUG Terminal Starting bolt terminal [1]
logger.ts:84 DEBUG Terminal Attach [terminal_0]
logger.ts:84 DEBUG Terminal Attach [terminal_1]
2webcontainer.fc837ba8.js:1 Uncaught (in promise) DataCloneError: Failed to execute 'postMessage' on 'Worker': SharedArrayBuffer transfer requires self.crossOriginIsolated.
    at iframe.main.fc837ba8.js:1:78426
    at new Promise (<anonymous>)
    at _0x22b8be (iframe.main.fc837ba8.js:1:77727)
    at Object.apply (iframe.main.fc837ba8.js:1:75697)
    at _0x1e9be3.init (iframe.main.fc837ba8.js:4:38574)Understand this errorAI
previews.ts:48 Uncaught (in promise) DataCloneError: Failed to execute 'postMessage' on 'Worker': SharedArrayBuffer transfer requires self.crossOriginIsolated.
    at iframe.main.fc837ba8.js:1:78426
    at new Promise (<anonymous>)
    at _0x22b8be (iframe.main.fc837ba8.js:1:77727)
    at Object.apply (iframe.main.fc837ba8.js:1:75697)
    at _0x1e9be3.init (iframe.main.fc837ba8.js:4:38574)Understand this errorAI
files.ts:123 Uncaught (in promise) DataCloneError: Failed to execute 'postMessage' on 'Worker': SharedArrayBuffer transfer requires self.crossOriginIsolated.
    at iframe.main.fc837ba8.js:1:78426
    at new Promise (<anonymous>)
    at _0x22b8be (iframe.main.fc837ba8.js:1:77727)
    at Object.apply (iframe.main.fc837ba8.js:1:75697)
    at _0x1e9be3.init (iframe.main.fc837ba8.js:4:38574)

### Platform

- OS: [Linux Ubuntu 22.04]
- Browser: [Chrome]
- Version: [e.g. 91.1]

**Comment by dustinwloring1988** [comment]
Are you running this repo in the cloud? If so is ollama running on that same machine? 
As for the OpenAI part not working maybe try updating your chrome install, any plugins running on chrome?

**Comment by antongo10** [comment]
Trying to run everything in the cloud on a single Ubuntu 22 machine (any advice for a good dev setup?)

Just tried starting it through remote RDP and using a local browser (localhost:5173) and ollama (127.0.0.1:11434) - WORKED, postMessage fixed, but failed to display the preview (api calls to webcontainers looks like a cors issue once again).

With openai on a local machine everything worked.

**Comment by dustinwloring1988** [comment]
@antongo10 I would try runpod.
I have a referral link here https://runpod.io?ref=kilq83n1

**Comment by dustinwloring1988** [comment]
They have an ollama template then just run bolt locally and set the ollama URL to the ollama instance or you can run both on the pod at the same time

**Comment by antongo10** [comment]
<img width="1470" alt="Screenshot 2024-12-03 at 19 13 10" src="https://github.com/user-attachments/assets/b1b77508-75b8-408c-bd2b-14990af9be2c">

Thank you
