### ISSUE TITLE
Console firing off ollama and other errors (using openrouter and claude)

### ISSUE THREAD

**Issue by brovio** [stackblitz-labs/bolt.diy#530]
### Describe the bug

hey guys, 

my local instance of bolt, is having issues creating anything but basic text..

I initially tried with importing a folder, which didn't work, which made me create a detailed MD file (which I needed to do anyway).

I installed ottodev in a new folder, not in docker, have changed the my env.whatever-it-was to just .env, and I can see openrouters is taking credits away from me, from both Qwen 2.5 coder, and then thinking that was the main issue, cluade 3.5 latest.

console is as follows:
C:\_Vault-G14\AI\BetterBolt\3\bolt.new-any-llm  main  -1  git pull
remote: Enumerating objects: 210, done.
remote: Counting objects: 100% (187/187), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 126 (delta 100), reused 104 (delta 78), pack-reused 0 (from 0
Receiving objects: 100% (126/126), 18.34 KiB | 2.29 MiB/s, done.
Resolving deltas: 100% (100/100), completed with 37 local objects.
From https://github.com/coleam00/bolt.new-any-llm
 * [new branch]      pr/332     -> origin/pr/332
Already up to date.
C:\_Vault-G14\AI\BetterBolt\3\bolt.new-any-llm  main  -1  pnpm install
Lockfile is up to date, resolution step is skipped
Already up to date

> bolt@ prepare C:\_Vault-G14\AI\BetterBolt\3\bolt.new-any-llm
> husky

Done in 1.6s
C:\_Vault-G14\AI\BetterBolt\3\bolt.new-any-llm  main  -1  pnpm run dev

> bolt@ dev C:\_Vault-G14\AI\BetterBolt\3\bolt.new-any-llm
> remix vite:dev

 warn  Data fetching is changing to a single fetch in React Router v7
┃ You can use the `v3_singleFetch` future flag to opt-in early.
┃ -> https://remix.run/docs/en/2.13.1/start/future-flags#v3_singleFetch
┗
  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
Error getting Ollama models: TypeError: fetch failed
    at node:internal/deps/undici/undici:13179:13
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at Object.getOllamaModels [as getDynamicModels] (C:/_Vault-G14/AI/BetterBolt/3/bolt.new-any-llm/app/utils/constants.ts:318:22)
    at async Promise.all (index 0)
    at Module.initializeModelList (C:/_Vault-G14/AI/BetterBolt/3/bolt.new-any-llm/app/utils/constants.ts:389:9)
    at handleRequest (C:/_Vault-G14/AI/BetterBolt/3/bolt.new-any-llm/app/entry.server.tsx:30:3)
    at handleDocumentRequest (C:\_Vault-G14\AI\BetterBolt\3\bolt.new-any-llm\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:340:12)
    at requestHandler (C:\_Vault-G14\AI\BetterBolt\3\bolt.new-any-llm\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:160:18)
    at C:\_Vault-G14\AI\BetterBolt\3\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_zyxju6yjkqxopc2lqyhhptpywm\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:70:25 {
  [cause]: AggregateError:
      at internalConnectMultiple (node:net:1116:18)
      at afterConnectMultiple (node:net:1683:7)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'ECONNREFUSED',
    [errors]: [ [Error], [Error] ]
  }
}
Error getting Ollama models: TypeError: fetch failed
    at node:internal/deps/undici/undici:13179:13
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at Object.getOllamaModels [as getDynamicModels] (C:/_Vault-G14/AI/BetterBolt/3/bolt.new-any-llm/app/utils/constants.ts:318:22)
    at async Promise.all (index 0)
    at Module.initializeModelList (C:/_Vault-G14/AI/BetterBolt/3/bolt.new-any-llm/app/utils/constants.ts:389:9)
    at handleRequest (C:/_Vault-G14/AI/BetterBolt/3/bolt.new-any-llm/app/entry.server.tsx:30:3)
    at handleDocumentRequest (C:\_Vault-G14\AI\BetterBolt\3\bolt.new-any-llm\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:340:12)
    at requestHandler (C:\_Vault-G14\AI\BetterBolt\3\bolt.new-any-llm\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:160:18)
    at C:\_Vault-G14\AI\BetterBolt\3\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_zyxju6yjkqxopc2lqyhhptpywm\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:70:25 {
  [cause]: AggregateError:
      at internalConnectMultiple (node:net:1116:18)
      at afterConnectMultiple (node:net:1683:7)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'ECONNREFUSED',
    [errors]: [ [Error], [Error] ]
  }
}
Error getting Ollama models: TypeError: fetch failed
    at node:internal/deps/undici/undici:13179:13
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at Object.getOllamaModels [as getDynamicModels] (C:/_Vault-G14/AI/BetterBolt/3/bolt.new-any-llm/app/utils/constants.ts:318:22)
    at async Promise.all (index 0)
    at Module.initializeModelList (C:/_Vault-G14/AI/BetterBolt/3/bolt.new-any-llm/app/utils/constants.ts:389:9)
    at handleRequest (C:/_Vault-G14/AI/BetterBolt/3/bolt.new-any-llm/app/entry.server.tsx:30:3)
    at handleDocumentRequest (C:\_Vault-G14\AI\BetterBolt\3\bolt.new-any-llm\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:340:12)
    at requestHandler (C:\_Vault-G14\AI\BetterBolt\3\bolt.new-any-llm\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:160:18)
    at C:\_Vault-G14\AI\BetterBolt\3\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_zyxju6yjkqxopc2lqyhhptpywm\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:70:25 {
  [cause]: AggregateError:
      at internalConnectMultiple (node:net:1116:18)
      at afterConnectMultiple (node:net:1683:7)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'ECONNREFUSED',
    [errors]: [ [Error], [Error] ]
  }
}
Error getting Ollama models: TypeError: fetch failed
    at node:internal/deps/undici/undici:13179:13
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at Object.getOllamaModels [as getDynamicModels] (C:/_Vault-G14/AI/BetterBolt/3/bolt.new-any-llm/app/utils/constants.ts:318:22)
    at async Promise.all (index 0)
    at Module.initializeModelList (C:/_Vault-G14/AI/BetterBolt/3/bolt.new-any-llm/app/utils/constants.ts:389:9)
    at handleRequest (C:/_Vault-G14/AI/BetterBolt/3/bolt.new-any-llm/app/entry.server.tsx:30:3)
    at handleDocumentRequest (C:\_Vault-G14\AI\BetterBolt\3\bolt.new-any-llm\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:340:12)
    at requestHandler (C:\_Vault-G14\AI\BetterBolt\3\bolt.new-any-llm\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:160:18)
    at C:\_Vault-G14\AI\BetterBolt\3\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_zyxju6yjkqxopc2lqyhhptpywm\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:70:25 {
  [cause]: AggregateError:
      at internalConnectMultiple (node:net:1116:18)
      at afterConnectMultiple (node:net:1683:7)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'ECONNREFUSED',
    [errors]: [ [Error], [Error] ]
  }
}
Error getting Ollama models: TypeError: fetch failed
    at node:internal/deps/undici/undici:13179:13
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at Object.getOllamaModels [as getDynamicModels] (C:/_Vault-G14/AI/BetterBolt/3/bolt.new-any-llm/app/utils/constants.ts:318:22)
    at async Promise.all (index 0)
    at Module.initializeModelList (C:/_Vault-G14/AI/BetterBolt/3/bolt.new-any-llm/app/utils/constants.ts:389:9)
    at handleRequest (C:/_Vault-G14/AI/BetterBolt/3/bolt.new-any-llm/app/entry.server.tsx:30:3)
    at handleDocumentRequest (C:\_Vault-G14\AI\BetterBolt\3\bolt.new-any-llm\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:340:12)
    at requestHandler (C:\_Vault-G14\AI\BetterBolt\3\bolt.new-any-llm\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:160:18)
    at C:\_Vault-G14\AI\BetterBolt\3\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_zyxju6yjkqxopc2lqyhhptpywm\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:70:25 {
  [cause]: AggregateError:
      at internalConnectMultiple (node:net:1116:18)
      at afterConnectMultiple (node:net:1683:7)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'ECONNREFUSED',
    [errors]: [ [Error], [Error] ]
  }
}

Sorry for all that, wasn't sure what would be best to use.

I did notice when I was using bolt.new, that from my current location in SEA, I was unable to use it. So I tried VPNing into US/AU/IE but nothing...

If I go into the bolt terminal, and CTRL C, it autoreboots to what seems to be an earlier version of the code when it was just testing sime text to let me know it was working. Asks me to press the stop button to kill the server, but I can't see one.

I'm sure this is a me issue and not a bolt issue.

Standard install was done with Admin PS:
git clone https://github.com/coleam00/bolt.new-any-llm.git
pnpm install
pnpm run dev

I have api's setup in the .env for more than one LLM (currently OpenAI, Anthropic, Gemini, Open Router and XAI) was unsure whether the values needed to be contained within the quotation marks which Open Router is, and is woking, so I've stuck to that.

I have Ollama installed on my PC, but not running, as in killed from system tray.

Upon start I do get this everytime:
 warn  Data fetching is changing to a single fetch in React Router v7
┃ You can use the `v3_singleFetch` future flag to opt-in early.
┃ -> https://remix.run/docs/en/2.13.1/start/future-flags#v3_singleFetch

but as it all loaded okay, didn't think it was an issue.

It's got to be a me issue. OpenRouter is taking next to nothing money wise, I notice that the node_module folder isn't there, try to run a npm install, but nothing.

It's gotta be a me thing. Just don't know where, hope ya'll can help me, or someone else like me who may run into this in the future.

Here's some images:
https://tinyurl.com/28hfkv2f
https://tinyurl.com/2yqwywhv
https://tinyurl.com/2ab3cvsd

PS tried shadcn, tailwind, and others...

### Link to the Bolt URL that caused the error

https://k03e2io1v3fx9wvj0vr8qd5q58o56n-fkdo--5173--fc837ba8.local-corp.webcontainer-api.io

### Steps to reproduce

Just what was mentioned above

### Expected behavior

creation of a visual component otheer than just text

### Platform

Windows 11 Pro
Chrome Latest as of Dec 4

### Provider Used

Anthropic

### Model Used

Cluade Sonnet 3.5 new, but tried others

**Comment by thecodacus** [comment]
ollama error is fine its just an warning, as it tried and failed to load ollama models because ollama is not running on your system
