### ISSUE TITLE
deepseek his model's maximum context length is 65536 tokens. However, you requested 190402 tokens (182402 in the messages, 8000 in the completion). Please reduce the length of the messages or completion.

### ISSUE THREAD

**Issue by tqangxl** [stackblitz-labs/bolt.diy#564]
### Describe the bug
deepseek-coder & deepseek-chat upgrade  ---> DeepSeek V2.5 模型
https://api-docs.deepseek.com/updates

APICallError [AI_APICallError]: This model's maximum context length is 65536 tokens. However, you requested 190402 tokens (182402 in the messages, 8000 in the completion). Please reduce the length of the messages or completion.
    at file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/@ai-sdk+provider-utils@1.0.20_zod@3.23.8/node_modules/@ai-sdk/provider-utils/src/response-handler.ts:58:16
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at postToApi (file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/@ai-sdk+provider-utils@1.0.20_zod@3.23.8/node_modules/@ai-sdk/provider-utils/src/post-to-api.ts:81:28)
    at OpenAIChatLanguageModel.doStream (file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/@ai-sdk+openai@0.0.66_zod@3.23.8/node_modules/@ai-sdk/openai/src/openai-chat-language-model.ts:386:50)
    at fn (file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:378:23)
    at file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/telemetry/record-span.ts:18:22
    at _retryWithExponentialBackoff (file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.7.2__zod@3.23.8/node_modules/ai/util/retry-with-exponential-backoff.ts:37:12)
    at startStep (file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:333:13)
    at fn (file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:414:11)
    at file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/telemetry/record-span.ts:18:22
    at chatAction (D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/app/routes/api.chat.ts:63:20)
    at Object.callRouteAction (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\data.js:36:16)
    at D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4899:19
    at callLoaderOrAction (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4963:16)
    at async Promise.all (index 0)
    at defaultDataStrategy (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4772:17)
    at callDataStrategyImpl (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4835:17)
    at callDataStrategy (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3992:19)
    at submit (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3755:21)
    at queryImpl (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3684:22)
    at Object.queryRoute (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3629:18)
    at handleResourceRequest (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:402:20)
    at requestHandler (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:156:18)
    at D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_zyxju6yjkqxopc2lqyhhptpywm\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:70:25 {
  cause: undefined,
  url: 'https://api.deepseek.com/beta/chat/completions',
  requestBodyValues: {
    model: 'deepseek-coder',
    logit_bias: undefined,
    logprobs: undefined,
    top_logprobs: undefined,
    user: undefined,
    parallel_tool_calls: undefined,
    max_tokens: 8000,
    temperature: 0,
    top_p: undefined,
    frequency_penalty: undefined,
    presence_penalty: undefined,
    stop: undefined,
    seed: undefined,
    max_completion_tokens: undefined,
    store: undefined,
    metadata: undefined,
    response_format: undefined,
    messages: [ [Object], [Object], [Object], [Object], [Object] ],
    tools: undefined,
    tool_choice: undefined,
    stream: true,
    stream_options: undefined
  },
  statusCode: 400,
  responseHeaders: {
    'access-control-allow-credentials': 'true',
    connection: 'keep-alive',
    'content-length': '294',
    'content-type': 'application/json',
    date: 'Fri, 06 Dec 2024 12:41:25 GMT',
    server: 'nginx/1.18.0 (Ubuntu)',
    'set-cookie': 'HWWAFSESID=beba55087c8778758df; path=/',
    vary: 'origin, access-control-request-method, access-control-request-headers',
    'x-ds-request-id': 'f8e6ac22-e151-4d12-90ee-42db3132161e',
    'x-ds-trace-id': '590458809572e80960cea6ec7a2431ea',
    'x-ratelimit-limit': '200',
    'x-ratelimit-remaining': '199'
  },
  responseBody: `{"error":{"message":"This model's maximum context length is 65536 tokens. However, you requested 190402 tokens (182402 in the messages, 8000 in the completion). Please reduce the length of the messages or completion.","type":"invalid_request_error","param":null,"code":"invalid_request_error"}}`,
  isRetryable: false,
  data: {
    error: {
      message: "This model's maximum context length is 65536 tokens. However, you requested 190402 tokens (182402 in the messages, 8000 in the completion). Please reduce the length of the messages or completion.",
      type: 'invalid_request_error',
      param: null,
      code: 'invalid_request_error'
    }
  },
  [Symbol(vercel.ai.error)]: true,
  [Symbol(vercel.ai.error.AI_APICallError)]: true

### Link to the Bolt URL that caused the error

chat

### Steps to reproduce

Prompt：
设计一套使用Next.js构建的高端企业官网，整体以橙色为主色调，UI设计简洁且富有现代感，突出高端大气。以下是具体要求：

整体布局：
主色调为橙色，搭配灰白等中性色，保持页面视觉和谐。
网站包含以下模块：导航栏、首页宣传语、产品介绍、公司介绍、团队展示、联系信息、页脚。
导航栏：
导航栏固定在页面顶部，包含首页、产品、关于我们、团队、联系我们等栏目。
支持中文与英文切换，提供语言选择按钮（CN/EN）。
首页宣传语：
居中显示公司主打宣传语，例如“创新引领未来”或“Empowering Innovation”。
配以橙色主题背景或动态效果，突出品牌形象。
产品介绍：
使用图文结合的卡片布局，每个产品块包含名称、简要描述、特色功能与CTA按钮（了解更多）。
提供鼠标悬停的交互效果，例如卡片微动或阴影变化。
公司介绍与团队展示：
公司介绍模块简洁明了，结合橙色元素，展示公司的愿景与核心价值观。
团队展示采用网格布局，每位成员头像下方标注姓名与职位，可点击查看详细介绍。
联系信息与页脚：
联系信息模块包括联系表单、电话、邮箱，以及公司地址的嵌入式地图。
页脚设计简洁，包含版权声明、友情链接、社交媒体图标等。
多语言支持：
所有模块内容提供中英文版本，可通过切换按钮即时切换语言。
其他要求：
网站自适应设计，支持PC端与移动端访问，确保流畅的用户体验。
首页加载动画简约，提升首屏吸引力。
输出代码结构清晰，利于维护与扩展，确保SEO优化。

### Expected behavior

There was an error processing your request: No details were returned

### Platform

- OS: [e.g. macOS, Windows, Linux]
- 版本	Windows 11 专业版
版本号	23H2
安装日期	‎2022/‎5/‎7
操作系统版本	22631.4460
体验	Windows Feature Experience Pack 1000.22700.1047.0

- Browser: 
Microsoft Edge
版本 131.0.2903.70 (正式版本) (64 位)
Chrome 已是最新版本
版本 131.0.6778.109（正式版本） （64 位）

### Model Used

deepseek-coder

**Comment by tqangxl** [comment]
APICallError [AI_APICallError]: Request Entity Too Large
    at file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/@ai-sdk+provider-utils@1.0.20_zod@3.23.8/node_modules/@ai-sdk/provider-utils/src/response-handler.ts:72:16
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at postToApi (file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/@ai-sdk+provider-utils@1.0.20_zod@3.23.8/node_modules/@ai-sdk/provider-utils/src/post-to-api.ts:81:28)
    at OpenAIChatLanguageModel.doStream (file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/@ai-sdk+openai@0.0.66_zod@3.23.8/node_modules/@ai-sdk/openai/src/openai-chat-language-model.ts:386:50)
    at fn (file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:378:23)
    at file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/telemetry/record-span.ts:18:22
    at _retryWithExponentialBackoff (file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.7.2__zod@3.23.8/node_modules/ai/util/retry-with-exponential-backoff.ts:37:12)
    at startStep (file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:333:13)
    at fn (file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:414:11)
    at file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/telemetry/record-span.ts:18:22
    at chatAction (D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/app/routes/api.chat.ts:63:20)
    at Object.callRouteAction (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\data.js:36:16)
    at D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4899:19
    at callLoaderOrAction (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4963:16)
    at async Promise.all (index 0)
    at defaultDataStrategy (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4772:17)
    at callDataStrategyImpl (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4835:17)
    at callDataStrategy (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3992:19)
    at submit (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3755:21)
    at queryImpl (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3684:22)
    at Object.queryRoute (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3629:18)
    at handleResourceRequest (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:402:20)
    at requestHandler (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:156:18)
    at D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_zyxju6yjkqxopc2lqyhhptpywm\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:70:25 {
  cause: undefined,
  url: 'https://api.deepseek.com/beta/chat/completions',
  requestBodyValues: {
    model: 'deepseek-coder',
    logit_bias: undefined,
    logprobs: undefined,
    top_logprobs: undefined,
    user: undefined,
    parallel_tool_calls: undefined,
    max_tokens: 128000,
    temperature: 0,
    top_p: undefined,
    frequency_penalty: undefined,
    presence_penalty: undefined,
    stop: undefined,
    seed: undefined,
    max_completion_tokens: undefined,
    store: undefined,
    metadata: undefined,
    response_format: undefined,
    messages: [ [Object], [Object], [Object], [Object] ],
    tools: undefined,
    tool_choice: undefined,
    stream: true,
    stream_options: undefined
  },
  statusCode: 413,
  responseHeaders: {
    connection: 'close',
    'content-length': '192',
    'content-type': 'text/html',
    date: 'Sat, 07 Dec 2024 10:49:39 GMT',
    server: 'nginx/1.18.0 (Ubuntu)'
  },
  responseBody: '<html>\r\n' +
    '<head><title>413 Request Entity Too Large</title></head>\r\n' +
    '<body>\r\n' +
    '<center><h1>413 Request Entity Too Large</h1></center>\r\n' +
    '<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n' +
    '</body>\r\n' +
    '</html>\r\n',
  isRetryable: false,
  data: undefined,
  [Symbol(vercel.ai.error)]: true,
  [Symbol(vercel.ai.error.AI_APICallError)]: true
}
APICallError [AI_APICallError]: Request Entity Too Large
    at file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/@ai-sdk+provider-utils@1.0.20_zod@3.23.8/node_modules/@ai-sdk/provider-utils/src/response-handler.ts:72:16
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at postToApi (file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/@ai-sdk+provider-utils@1.0.20_zod@3.23.8/node_modules/@ai-sdk/provider-utils/src/post-to-api.ts:81:28)
    at OpenAIChatLanguageModel.doStream (file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/@ai-sdk+openai@0.0.66_zod@3.23.8/node_modules/@ai-sdk/openai/src/openai-chat-language-model.ts:386:50)
    at fn (file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:378:23)
    at file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/telemetry/record-span.ts:18:22
    at _retryWithExponentialBackoff (file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.7.2__zod@3.23.8/node_modules/ai/util/retry-with-exponential-backoff.ts:37:12)
    at startStep (file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:333:13)
    at fn (file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:414:11)
    at file:///D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/telemetry/record-span.ts:18:22
    at chatAction (D:/Lib/Dev/AI/bolt.new/bolt.new-any-llm/app/routes/api.chat.ts:63:20)
    at Object.callRouteAction (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\data.js:36:16)
    at D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4899:19
    at callLoaderOrAction (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4963:16)
    at async Promise.all (index 0)
    at defaultDataStrategy (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4772:17)
    at callDataStrategyImpl (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4835:17)
    at callDataStrategy (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3992:19)
    at submit (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3755:21)
    at queryImpl (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3684:22)
    at Object.queryRoute (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3629:18)
    at handleResourceRequest (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:402:20)
    at requestHandler (D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:156:18)
    at D:\Lib\Dev\AI\bolt.new\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_zyxju6yjkqxopc2lqyhhptpywm\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:70:25 {
  cause: undefined,
  url: 'https://api.deepseek.com/beta/chat/completions',
  requestBodyValues: {
    model: 'deepseek-coder',
    logit_bias: undefined,
    logprobs: undefined,
    top_logprobs: undefined,
    user: undefined,
    parallel_tool_calls: undefined,
    max_tokens: 128000,
    temperature: 0,
    top_p: undefined,
    frequency_penalty: undefined,
    presence_penalty: undefined,
    stop: undefined,
    seed: undefined,
    max_completion_tokens: undefined,
    store: undefined,
    metadata: undefined,
    response_format: undefined,
    messages: [ [Object], [Object], [Object], [Object] ],
    tools: undefined,
    tool_choice: undefined,
    stream: true,
    stream_options: undefined
  },
  statusCode: 413,
  responseHeaders: {
    connection: 'close',
    'content-length': '192',
    'content-type': 'text/html',
    date: 'Sat, 07 Dec 2024 10:50:36 GMT',
    server: 'nginx/1.18.0 (Ubuntu)'
  },
  responseBody: '<html>\r\n' +
    '<head><title>413 Request Entity Too Large</title></head>\r\n' +
    '<body>\r\n' +
    '<center><h1>413 Request Entity Too Large</h1></center>\r\n' +
    '<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n' +
    '</body>\r\n' +
    '</html>\r\n',
  isRetryable: false,
  data: undefined,
  [Symbol(vercel.ai.error)]: true,
  [Symbol(vercel.ai.error.AI_APICallError)]: true
