### ISSUE TITLE
Error getting OpenAILike models: TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by dreher-in** [stackblitz-labs/bolt.diy#652]
### Describe the bug

Just pulled the latest version (mine was still oTTodev, now the latest bolt.diy) and rebuilt my docker stack. Now the OpenAILike seems broken and stopped working. Before the upgrade it worked, so I assume it's not a problem on my side.

```
docker compose --profile development --env-file .env.local up --build
WARN[0000] The "TOGETHER_API_KEY" variable is not set. Defaulting to a blank string. 
WARN[0000] The "TOGETHER_API_BASE_URL" variable is not set. Defaulting to a blank string. 
WARN[0000] The "TOGETHER_API_KEY" variable is not set. Defaulting to a blank string. 
 => => naming to docker.io/library/bolt-ai:development                                                                                                               0.0s
 => [app-dev] resolving provenance for metadata file                                                                                                                 0.0s
WARN[0003] Found orphan containers ([boltnew-any-llm-bolt-ai-dev-1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Running 1/1
 ✔ Container boltnew-any-llm-app-dev-1  Recreated                                                                                                                    1.0s 
Attaching to app-dev-1
app-dev-1  | 
app-dev-1  | > bolt@ dev /app
app-dev-1  | > remix vite:dev "--host" "0.0.0.0"
app-dev-1  | 
app-dev-1  | [warn] Route discovery/manifest behavior is changing in React Router v7
app-dev-1  | ┃ You can use the `v3_lazyRouteDiscovery` future flag to opt-in early.
app-dev-1  | ┃ -> https://remix.run/docs/en/2.13.1/start/future-flags#v3_lazyRouteDiscovery
app-dev-1  | ┗
app-dev-1  | [warn] Data fetching is changing to a single fetch in React Router v7
app-dev-1  | ┃ You can use the `v3_singleFetch` future flag to opt-in early.
app-dev-1  | ┃ -> https://remix.run/docs/en/2.13.1/start/future-flags#v3_singleFetch
app-dev-1  | ┗
app-dev-1  |   ➜  Local:   http://localhost:5173/
app-dev-1  |   ➜  Network: http://192.168.0.2:5173/
app-dev-1  | Error getting OpenAILike models: TypeError: Cannot read properties of undefined (reading 'map')
app-dev-1  |     at Object.getOpenAILikeModels [as getDynamicModels] (/app/app/utils/constants.ts:400:21)
app-dev-1  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
app-dev-1  |     at async Promise.all (index 1)
app-dev-1  |     at Module.initializeModelList (/app/app/utils/constants.ts:457:9)
app-dev-1  |     at handleRequest (/app/app/entry.server.tsx:30:3)
app-dev-1  |     at handleDocumentRequest (/app/node_modules/.pnpm/@remix-run+server-runtime@2.15.0_typescript@5.7.2/node_modules/@remix-run/server-runtime/dist/server.js:340:12)
app-dev-1  |     at requestHandler (/app/node_modules/.pnpm/@remix-run+server-runtime@2.15.0_typescript@5.7.2/node_modules/@remix-run/server-runtime/dist/server.js:160:18)
app-dev-1  |     at /app/node_modules/.pnpm/@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_3djlhh3t6jbfog2cydlrvgreoy/node_modules/@remix-run/dev/dist/vite/cloudflare-proxy-plugin.js:70:25
```

On the litellm side I can see:
`litellm-1     | {"message": "litellm.proxy.proxy_server.user_api_key_auth(): Exception occured - Malformed API Key passed in. Ensure Key has `Bearer ` prefix. Passed in: Bearer\nRequester IP Address:192.168.178.8", "level": "ERROR", "timestamp": "2024-12-11T21:03:08.435971", "stacktrace": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/litellm/proxy/auth/user_api_key_auth.py\", line 569, in user_api_key_auth\n    raise Exception(\nException: Malformed API Key passed in. Ensure Key has `Bearer ` prefix. Passed in: Bearer"}`

### Link to the Bolt URL that caused the error

NA, local

### Steps to reproduce

Clone the current git and configure OPENAI_LIKE_API_BASE_URL and OPENAI_LIKE_API_KEY in .env.local and start it.

### Expected behavior

Working OpenAILike models, here litellm 

### Platform

- OS: Debian 12
- Browser: NA
- Version: [cf21dde](https://github.com/stackblitz-labs/bolt.diy/commit/cf21dde102b8d6b2693b35ab263b7deeb60b24df)

### Provider Used

Litellm

### Model Used

NA

**Comment by dreher-in** [comment]
Did some further debugging. Found out the bolt is missing to send out the API key, see here:

```
2024/12/11 22:33:06 request received:
GET /models HTTP/1.1
Host: 192.168.178.250:8222
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: *
Authorization: Bearer
Connection: keep-alive
Sec-Fetch-Mode: cors
User-Agent: node
```

OPENAI_LIKE_API_KEY is properly set.

**Comment by dreher-in** [comment]
Dirty fix for me in `app/utils/constants.ts`:

Line 410: `let apiKey = import.meta.env.OPENAI_LIKE_API_KEY;`

Seems there is an issue with the following lines:

```
    if (apiKeys && apiKeys.OpenAILike) {
      apiKey = apiKeys.OpenAILike;
    }
```

I am not so deep into the codebase, to quickly spot whats wrong.

**Comment by bgoosmanviz** [comment]
Same here

**Comment by arieltoledo** [comment]
I just made a docker system prune, clone the repo again I now the container shuts down inmediatly. 
Log from the container:
`> bolt@ dev /app
> remix vite:dev "--host" "0.0.0.0"

Error: Route segment "ts:Zone" for "api.enhancer.ts:Zone" cannot contain ":".
If this is something you need, upvote this proposal for React Router https://github.com/remix-run/react-router/discussions/9822.
    at notSupportedInRR (/app/node_modules/.pnpm/@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge/node_modules/@remix-run/dev/dist/config/flat-routes.js:270:13)
    at pushRouteSegment (/app/node_modules/.pnpm/@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge/node_modules/@remix-run/dev/dist/config/flat-routes.js:276:14)
    at getRouteSegments (/app/node_modules/.pnpm/@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge/node_modules/@remix-run/dev/dist/config/flat-routes.js:375:3)
    at flatRoutesUniversal (/app/node_modules/.pnpm/@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge/node_modules/@remix-run/dev/dist/config/flat-routes.js:130:27)
    at Object.flatRoutes (/app/node_modules/.pnpm/@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge/node_modules/@remix-run/dev/dist/config/flat-routes.js:97:23)
    at Object.resolveConfig (/app/node_modules/.pnpm/@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge/node_modules/@remix-run/dev/dist/config.js:167:33)
    at async updateRemixPluginContext (/app/node_modules/.pnpm/@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge/node_modules/@remix-run/dev/dist/vite/plugin.js:366:9)
    at async config (/app/node_modules/.pnpm/@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge/node_modules/@remix-run/dev/dist/vite/plugin.js:601:7)
    at async runConfigHook (file:///app/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:66942:19)
    at async resolveConfig (file:///app/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:66393:12)
 ELIFECYCLE  Command failed with exit code 1.`

**Comment by yodaljit** [comment]
fixed this issue in #693 . The error was that Anthropic was always the default provider even after switching the provider to OpenAILike or OpenRouter. So only the Anthropic models was loaded. Now the models are loaded from the selected provider without any issue.

**Comment by thecodacus** [comment]
@dreher-in try setting the apikey on the UI and check,

I would suggest pull the latest branch and then do the following

add the url on the settings tab
![image](https://github.com/user-attachments/assets/a41658d8-26e5-4155-b67d-9cfed6bd3e41)

then add the api key on the chatbox
![image](https://github.com/user-attachments/assets/ddd8e04b-7dda-4c2c-bd80-cc97c3ee1f11)


please let Us know is the issue is resolved. need feedback to understand the exact problem

**Comment by jiaohuix** [comment]
@thecodacus  hi,  I'm also encountering an issue similar , could you please advise on how to access the web UI to configure the API key?

**Comment by thecodacus** [comment]
you can access the settings menu at the left sidebar. bottom left corner
![image](https://github.com/user-attachments/assets/894abc6d-5926-4618-99bc-e22f1e326332)

**Comment by jiaohuix** [comment]
@thecodacus   Ohhh Thank you! However, I’m encountering an issue with the OpenAILike model.

I followed your instructions: I first set the urlBase in the settings, and then entered my API key in the “OpenAILike API Key:” field. After refreshing the website, the model list appeared correctly, as shown below:
![image](https://github.com/user-attachments/assets/cb2de0f5-d858-4749-8083-b440ff6d264f)

However, when I attempt to chat with the GPT model, I receive an error message. Unfortunately, I am unable to upload the error message image at this time.
![image](https://github.com/user-attachments/assets/3e7060a0-4a82-40de-952f-6ca7605d0217)

Could you please advise on how to resolve this issue?"

**Comment by thecodacus** [comment]
do you see any errors in terminal ?

**Comment by thecodacus** [comment]
also the version looks old can you try the latest stable version ?

**Comment by turkeyallstar** [comment]
I can't manage to use both 'GPT-4' and 'OpenAI-like' on Bolt."

![Ekran görüntüsü 2024-12-19 000036](https://github.com/user-attachments/assets/80c8cd45-27ca-405f-a7a4-d51f002a3a36)

**Comment by thecodacus** [comment]
@turkeyallstar , this is is a separate issue, I am already checking the same issue which was actually created for this error.
can you please use that thread to report the issue

**Comment by muzafferkadir** [comment]
can you try with changing these lines
app/lib/modules/llm/providers/openai-like.ts 43-47 with:

```
return res.map((model: any) => ({
        name: model.name,
        label: model.name,
        provider: this.name,
        maxTokenAllowed: 8000,
      }));
```

**Comment by turkeyallstar** [comment]
> can you try with changing these lines app/lib/modules/llm/providers/openai-like.ts 43-47 with:
> 
> ```
> return res.map((model: any) => ({
>         name: model.name,
>         label: model.name,
>         provider: this.name,
>         maxTokenAllowed: 8000,
>       }));
> ```

--Cevabın için teşekkür ederim. bu kez de OpenAlLike yi seçtiğimde dil modelleri yandaki kutucukta açılmadı. 
--"Thank you for your answer. This time, when I selected OpenAlLike, the language models didn't open in the box next to it."

**Comment by furaar** [comment]
## Issue
app/lib/modules/llm/base-provider.ts 40-42
```js
const apiKey =
      apiKeys?.[this.name] || serverEnv?.[apiTokenKey] || process?.env?.[apiTokenKey] || manager.env?.[baseUrlKey];
```
this line ensures apiKey falls back to the baseUrl if there is nothing inside serverEnv or process.env - so it doesnt just return undefined.

But even if the env variables are properly set, it still falls back to baseUrl which causes the /models request header to bears the baseurl rather than the apikey:

```json
Authorization
	Bearer https://example.com/api/openai/v1
```

## Debugging
When I try to namely read the variables just before this line, it comes back perfectly fine:
```
console.log(process.env.OPENAI_LIKE_API_KEY, process.env.OPENAI_LIKE_API_BASE_URL);
```
```
app-dev-1  | myfakeapikey https://example.com/api/openai/v1
```
And when all of this data is then returned to app/lib/modules/llm/providers/openai-like.ts Line 24. - I try to read it again before line 36 (the fetch request) --- It returns fine.
```js
console.log(baseUrl, apiKey);
```
```sh
app-dev-1  | https://example.com/api/openai/v1 myfakeapikey
```

The moment the fetch request is made, the process.env value is undefined and it falls back to baseUrl. Setting the key in UI works fine, just not env. I need it in env :(

**Comment by thecodacus** [comment]
> app/lib/modules/llm/base-provider.ts 40-42
> 
> const apiKey =
>       apiKeys?.[this.name] || serverEnv?.[apiTokenKey] || process?.env?.[apiTokenKey] || manager.env?.[baseUrlKey];

this has been fixed in this [PR](https://github.com/stackblitz-labs/bolt.diy/pull/1063)

**Comment by pswai** [comment]
For some reason my provider return `undefined` here on the first fetch but ok in subsequent fetches. I'm not sure why but probably here can check for `res.data` to be an array.

https://github.com/stackblitz-labs/bolt.diy/blob/main/app/lib/modules/llm/providers/openai-like.ts#L42
