### ISSUE TITLE
Unable to run local LLM. Always searching for mistralai/mistral-nemo !!!

### ISSUE THREAD

**Issue by macnux** [stackblitz-labs/bolt.diy#661]
### Describe the bug

I have Ollama installed and working locally.
I installed bolt.diy and set the OLLAMA_API_BASE_URL=http://localhost:11434 and renamed the file to .env.local  
When I open the browser, it shows the local LLM installed which is Qwen-coder but when I start chatting I get an error:

```
APICallError [AI_APICallError]: Not Found
    at C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@ai-sdk+provider-utils@1.0.20_zod@3.23.8\node_modules\@ai-sdk\provider-utils\src\response-handler.ts:72:16
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at postToApi (C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@ai-sdk+provider-utils@1.0.20_zod@3.23.8\node_modules\@ai-sdk\provider-utils\src\post-to-api.ts:81:28)
    at OllamaChatLanguageModel.doStream (C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\ollama-ai-provider@0.15.2_zod@3.23.8\node_modules\ollama-ai-provider\src\ollama-chat-language-model.ts:230:50)
    at fn (file:///C:/Users/Mokhtar/Downloads/bolt.diy/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@5.4.0__svelte@5.4.0_vue@3.5.13_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:378:23)
    at file:///C:/Users/Mokhtar/Downloads/bolt.diy/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@5.4.0__svelte@5.4.0_vue@3.5.13_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/telemetry/record-span.ts:18:22
    at _retryWithExponentialBackoff (file:///C:/Users/Mokhtar/Downloads/bolt.diy/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@5.4.0__svelte@5.4.0_vue@3.5.13_typescript@5.7.2__zod@3.23.8/node_modules/ai/util/retry-with-exponential-backoff.ts:37:12)
    at startStep (file:///C:/Users/Mokhtar/Downloads/bolt.diy/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@5.4.0__svelte@5.4.0_vue@3.5.13_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:333:13)
    at fn (file:///C:/Users/Mokhtar/Downloads/bolt.diy/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@5.4.0__svelte@5.4.0_vue@3.5.13_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:414:11)
    at file:///C:/Users/Mokhtar/Downloads/bolt.diy/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@5.4.0__svelte@5.4.0_vue@3.5.13_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/telemetry/record-span.ts:18:22
    at chatAction (C:/Users/Mokhtar/Downloads/bolt.diy/app/routes/api.chat.ts:66:20)
    at Object.callRouteAction (C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\data.js:36:16)
    at C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4899:19
    at callLoaderOrAction (C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4963:16)
    at async Promise.all (index 0)
    at defaultDataStrategy (C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4772:17)
    at callDataStrategyImpl (C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4835:17)
    at callDataStrategy (C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3992:19)
    at submit (C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3755:21)
    at queryImpl (C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3684:22)
    at Object.queryRoute (C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3629:18)
    at handleResourceRequest (C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:402:20)
    at requestHandler (C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:156:18)
    at C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_3djlhh3t6jbfog2cydlrvgreoy\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:70:25 {
  cause: undefined,
  url: 'http://localhost:11434/api/chat',
  requestBodyValues: {
    format: undefined,
    model: 'mistralai/mistral-nemo',
    options: { num_ctx: 8192, num_predict: 8000, temperature: 0 },
    messages: [ [Object], [Object] ],
    tools: undefined
  },
  statusCode: 404,
  responseHeaders: {
    'content-length': '76',
    'content-type': 'application/json; charset=utf-8',
    date: 'Thu, 12 Dec 2024 08:24:15 GMT'
  },
  responseBody: '{"error":"model \\"mistralai/mistral-nemo\\" not found, try pulling it first"}',
  isRetryable: false,
  data: undefined,
  [Symbol(vercel.ai.error)]: true,
  [Symbol(vercel.ai.error.AI_APICallError)]: true
}
```
It searches for mistralai/mistral-nemo although it is not installed at all.
I tried different local LLMs, but the same issue.

### Link to the Bolt URL that caused the error

http://localhost:5173/

### Steps to reproduce

Open http://localhost:5173/ and try to chat with locally installed llm.
it will return an error and it searches for a non-installed LLM

### Expected behavior

It should work without errors

### Platform

- OS: Windows 11
- Browser: Chrome
- Version: 131.0.6778.139

**Comment by ravindranantony** [comment]
instead of localhost use OLLAMA_API_BASE_URL=http://127.0.0.1:11434 since localhost pointing ipv6

**Comment by macnux** [comment]
works!

**Comment by macnux** [comment]
It works once and after closing and reopening it searches for Sonnet!!!

```
APICallError [AI_APICallError]: Not Found
    at C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@ai-sdk+provider-utils@1.0.20_zod@3.23.8\node_modules\@ai-sdk\provider-utils\src\response-handler.ts:72:16
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at postToApi (C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@ai-sdk+provider-utils@1.0.20_zod@3.23.8\node_modules\@ai-sdk\provider-utils\src\post-to-api.ts:81:28)
    at OllamaChatLanguageModel.doStream (C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\ollama-ai-provider@0.15.2_zod@3.23.8\node_modules\ollama-ai-provider\src\ollama-chat-language-model.ts:230:50)
    at fn (file:///C:/Users/Mokhtar/Downloads/bolt.diy/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@5.4.0__svelte@5.4.0_vue@3.5.13_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:378:23)
    at file:///C:/Users/Mokhtar/Downloads/bolt.diy/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@5.4.0__svelte@5.4.0_vue@3.5.13_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/telemetry/record-span.ts:18:22
    at _retryWithExponentialBackoff (file:///C:/Users/Mokhtar/Downloads/bolt.diy/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@5.4.0__svelte@5.4.0_vue@3.5.13_typescript@5.7.2__zod@3.23.8/node_modules/ai/util/retry-with-exponential-backoff.ts:37:12)
    at startStep (file:///C:/Users/Mokhtar/Downloads/bolt.diy/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@5.4.0__svelte@5.4.0_vue@3.5.13_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:333:13)
    at fn (file:///C:/Users/Mokhtar/Downloads/bolt.diy/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@5.4.0__svelte@5.4.0_vue@3.5.13_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:414:11)
    at file:///C:/Users/Mokhtar/Downloads/bolt.diy/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@5.4.0__svelte@5.4.0_vue@3.5.13_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/telemetry/record-span.ts:18:22
    at chatAction (C:/Users/Mokhtar/Downloads/bolt.diy/app/routes/api.chat.ts:66:20)
    at Object.callRouteAction (C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\data.js:36:16)
    at C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4899:19
    at callLoaderOrAction (C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4963:16)
    at async Promise.all (index 0)
    at defaultDataStrategy (C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4772:17)
    at callDataStrategyImpl (C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4835:17)
    at callDataStrategy (C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3992:19)
    at submit (C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3755:21)
    at queryImpl (C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3684:22)
    at Object.queryRoute (C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3629:18)
    at handleResourceRequest (C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:402:20)
    at requestHandler (C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:156:18)
    at C:\Users\Mokhtar\Downloads\bolt.diy\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_3djlhh3t6jbfog2cydlrvgreoy\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:70:25 {
  cause: undefined,
  url: 'http://127.0.0.1:11434/api/chat',
  requestBodyValues: {
    format: undefined,
    model: 'claude-3-5-sonnet-latest',
    options: { num_ctx: 32768, num_predict: 8000, temperature: 0 },
    messages: [ [Object], [Object] ],
    tools: undefined
  },
  statusCode: 404,
  responseHeaders: {
    'content-length': '78',
    'content-type': 'application/json; charset=utf-8',
    date: 'Thu, 12 Dec 2024 20:38:20 GMT'
  },
  responseBody: '{"error":"model \\"claude-3-5-sonnet-latest\\" not found, try pulling it first"}',
  isRetryable: false,
  data: undefined,
  [Symbol(vercel.ai.error)]: true,
  [Symbol(vercel.ai.error.AI_APICallError)]: true
}
```
