### ISSUE TITLE
Docker Error Starting Development

### ISSUE THREAD

**Issue by gczako** [stackblitz-labs/bolt.diy#674]
### Describe the bug

When you use the docker-compose command it starts then hangs and gives errors regarding UI components and Vite. I have verified the files do exist in the repository and have attached the log from docker. Everything is using the latest Windows, Docker, and Bolt.diy Repo. The error still loads a page, but none of the buttons are working and the only dropdown that works is the LLM dropdown. Just for clarification I previously had the Ottodev, and bolt.new-any-llm running and working, deleted the old containers and cloned new repo to a new folder.

2024-12-12 17:44:32 > bolt@ dev /app
2024-12-12 17:44:32 > node pre-start.cjs;  remix vite:dev "--host" "0.0.0.0"
2024-12-12 17:44:32 
2024-12-12 17:44:32 
2024-12-12 17:44:32 ★═══════════════════════════════════════★
2024-12-12 17:44:32           B O L T . D I Y
2024-12-12 17:44:32          ⚡️  Welcome  ⚡️
2024-12-12 17:44:32 ★═══════════════════════════════════════★
2024-12-12 17:44:32 
2024-12-12 17:44:32 📍 Current Commit Version: e7859a34ae64dfac73bbf6fb9e243dc0a7be0a09
2024-12-12 17:44:32 ★═══════════════════════════════════════★
2024-12-12 17:44:47   ➜  Local:   http://localhost:5173/
2024-12-12 17:44:47   ➜  Network: http://IP_ADDRESS:5173/
2024-12-12 17:44:34 [warn] Route discovery/manifest behavior is changing in React Router v7
2024-12-12 17:44:34 ┃ You can use the `v3_lazyRouteDiscovery` future flag to opt-in early.
2024-12-12 17:44:34 ┃ -> https://remix.run/docs/en/2.13.1/start/future-flags#v3_lazyRouteDiscovery
2024-12-12 17:44:34 ┗
2024-12-12 17:44:34 [warn] Data fetching is changing to a single fetch in React Router v7
2024-12-12 17:44:34 ┃ You can use the `v3_singleFetch` future flag to opt-in early.
2024-12-12 17:44:34 ┃ -> https://remix.run/docs/en/2.13.1/start/future-flags#v3_singleFetch
2024-12-12 17:44:34 ┗
2024-12-12 17:45:21 WARN Constants Failed to get Ollama models:  fetch failed
2024-12-12 17:45:22 WARN Constants Failed to get Ollama models:  fetch failed
2024-12-12 17:45:34 10:45:34 PM [vite] Pre-transform error: Failed to resolve import "@codemirror/lang-vue" from "app/components/editor/codemirror/languages.ts". Does the file exist?
2024-12-12 17:45:35 10:45:35 PM [vite] Pre-transform error: Failed to resolve import "@radix-ui/react-switch" from "app/components/ui/Switch.tsx". Does the file exist?
2024-12-12 17:45:35 10:45:35 PM [vite] Pre-transform error: Failed to resolve import "@radix-ui/react-switch" from "app/components/ui/Switch.tsx". Does the file exist?
2024-12-12 17:45:38 10:45:38 PM [vite] ✨ new dependencies optimized: remix-island, ai/react, framer-motion, node:path, jszip, file-saver, @octokit/rest, date-fns, @radix-ui/react-dialog, react-resizable-panels, diff, istextorbinary, @codemirror/autocomplete, @codemirror/commands, @codemirror/language, @codemirror/search, @codemirror/state, @codemirror/view, @radix-ui/react-dropdown-menu, react-markdown, @uiw/codemirror-theme-vscode, @codemirror/lang-javascript, @codemirror/lang-html, @codemirror/lang-css, @codemirror/lang-sass, @codemirror/lang-json, @codemirror/lang-markdown, @codemirror/lang-wast, @codemirror/lang-python, @codemirror/lang-cpp, rehype-raw, remark-gfm, rehype-sanitize, unist-util-visit, shiki, @xterm/addon-fit, @xterm/addon-web-links, @xterm/xterm
2024-12-12 17:45:38 10:45:38 PM [vite] ✨ optimized dependencies changed. reloading
2024-12-12 17:45:41 10:45:41 PM [vite] Pre-transform error: Failed to resolve import "@radix-ui/react-switch" from "app/components/ui/Switch.tsx". Does the file exist?
2024-12-12 17:45:41 10:45:41 PM [vite] Pre-transform error: Failed to resolve import "@radix-ui/react-switch" from "app/components/ui/Switch.tsx". Does the file exist?
2024-12-12 17:45:42 10:45:42 PM [vite] Pre-transform error: Failed to resolve import "@codemirror/lang-vue" from "app/components/editor/codemirror/languages.ts". Does the file exist?
2024-12-12 17:45:42 The file does not exist at "/app/node_modules/.vite/deps/chunk-2GCAZTI3.js?v=a4f432d0" which is in the optimize deps directory. The dependency might be incompatible with the dep optimizer. Try adding it to `optimizeDeps.exclude`.
2024-12-12 17:45:45 10:45:45 PM [vite] Internal server error: Failed to resolve import "@codemirror/lang-vue" from "app/components/editor/codemirror/languages.ts". Does the file exist?
2024-12-12 17:45:45   Plugin: vite:import-analysis
2024-12-12 17:45:45   File: /app/app/components/editor/codemirror/languages.ts:8:20
2024-12-12 17:45:45   12 |      extensions: ["vue"],
2024-12-12 17:45:45   13 |      async load() {
2024-12-12 17:45:45   14 |        return import("@codemirror/lang-vue").then((module) => module.vue());
2024-12-12 17:45:45      |                      ^
2024-12-12 17:45:45   15 |      }
2024-12-12 17:45:45   16 |    }),
2024-12-12 17:45:45       at TransformPluginContext._formatError (file:///app/node_modules/.pnpm/vite@5.4.11_sass-embedded@1.81.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:49255:41)
2024-12-12 17:45:45       at TransformPluginContext.error (file:///app/node_modules/.pnpm/vite@5.4.11_sass-embedded@1.81.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:49250:16)
2024-12-12 17:45:45       at normalizeUrl (file:///app/node_modules/.pnpm/vite@5.4.11_sass-embedded@1.81.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:64041:23)
2024-12-12 17:45:45       at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-12-12 17:45:45       at file:///app/node_modules/.pnpm/vite@5.4.11_sass-embedded@1.81.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:64173:39
2024-12-12 17:45:45       at async Promise.all (index 4)
2024-12-12 17:45:45       at TransformPluginContext.transform (file:///app/node_modules/.pnpm/vite@5.4.11_sass-embedded@1.81.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:64100:7)
2024-12-12 17:45:45       at PluginContainer.transform (file:///app/node_modules/.pnpm/vite@5.4.11_sass-embedded@1.81.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:49096:18)
2024-12-12 17:45:45       at loadAndTransform (file:///app/node_modules/.pnpm/vite@5.4.11_sass-embedded@1.81.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:51929:27)
2024-12-12 17:45:45       at viteTransformMiddleware (file:///app/node_modules/.pnpm/vite@5.4.11_sass-embedded@1.81.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:61881:24)

### Link to the Bolt URL that caused the error

localhost:5173

### Steps to reproduce

1. Run command "docker-compose --profile development up"
2. Server starts...
3. Hangs
4. Terminal and log spit out above errors.

### Expected behavior

localhost:5173 to load a working bolt.diy 

### Screen Recording / Screenshot

https://app.screencastify.com/v3/watch/oZ6YqGYvzo5eoyub1FSk

![error starting](https://github.com/user-attachments/assets/ffd9577b-6b1c-442e-b552-b1cbf4db6c1b)

### Platform

- OS: [Windows 11]
- Browser: [Chrome, Edge]

**Comment by wolverin0** [comment]
set this on the settings > provider > ollama 

http://host.docker.internal:11434
