### ISSUE TITLE
Can't run profile production

### ISSUE THREAD

**Issue by ddiawara** [stackblitz-labs/bolt.diy#724]
### Describe the bug

[+] Running 1/0
 ✔ Container boltdiy-app-prod-1  Created                                                                                     0.0s 
Attaching to app-prod-1
app-prod-1  | 
app-prod-1  | > bolt@0.0.1 dockerstart /app
app-prod-1  | > bindings=$(./bindings.sh) && wrangler pages dev ./build/client $bindings --ip ******* --port 5173 --no-show-interactive-dev-session
app-prod-1  | 
app-prod-1  | ./bindings.sh: line 12: .env.local: No such file or directory
app-prod-1  | 
app-prod-1  |  ⛅️ wrangler 3.91.0 (update available 3.95.0)
app-prod-1  | ---------------------------------------------
app-prod-1  | 
app-prod-1  | ✨ Compiled Worker successfully
app-prod-1  | [wrangler:inf] Ready on http://*******:5173
app-prod-1  | [wrangler:inf] - http://*********:5173
app-prod-1  | [wrangler:inf] - http://*************:5173
app-prod-1  | ⎔ Starting local server...

### Link to the Bolt URL that caused the error

http://*********:5173

### Steps to reproduce

git clone -b stable https://github.com/stackblitz-labs/bolt.diy  
mv .env.example .env.local  

### Expected behavior

[+] Running 1/0
 ✔ Container boltdiy-app-prod-1  Recreated                                                                                   0.1s 
Attaching to app-prod-1
app-prod-1  | 
app-prod-1  | > bolt@0.0.1 dockerstart /app
app-prod-1  | > bindings=$(./bindings.sh) && wrangler pages dev ./build/client $bindings --ip ******* --port 5173 --no-show-interactive-dev-session
app-prod-1  | 
app-prod-1  | ./bindings.sh: line 12: .env.local: No such file or directory
app-prod-1  | 
app-prod-1  |  ⛅️ wrangler 3.91.0 (update available 3.95.0)
app-prod-1  | ---------------------------------------------
app-prod-1  | 
app-prod-1  | ✨ Compiled Worker successfully
app-prod-1  | [wrangler:inf] Ready on http://*******:5173
app-prod-1  | [wrangler:inf] - http://*********:5173
app-prod-1  | [wrangler:inf] - http://*************:5173
app-prod-1  | ⎔ Starting local server...
app-prod-1  | [WARN] Failed to get Ollama models:  Network connection lost.
app-prod-1  | [wrangler:inf] GET / 200 OK (1165ms)
app-prod-1  | [wrangler:inf] GET /assets/root-DIfmt_Zi.css 200 OK (19ms)
app-prod-1  | [wrangler:inf] GET /assets/ReactToastify-Bh76j7cs.css 200 OK (30ms)
app-prod-1  | [wrangler:inf] GET /assets/Header-C6KxNF4z.css 200 OK (12ms)
app-prod-1  | [wrangler:inf] GET /assets/manifest-e7d7f48d.js 200 OK (12ms)
app-prod-1  | [wrangler:inf] GET /assets/tailwind-compat-Bwh-BmjE.css 200 OK (35ms)
app-prod-1  | [wrangler:inf] GET /assets/index-BNYgI3gK.css 200 OK (45ms)
app-prod-1  | [wrangler:inf] GET /assets/_index-CK3iMQik.css 200 OK (61ms)
app-prod-1  | [wrangler:inf] GET /assets/theme-DxrHHsjg.js 200 OK (17ms)
app-prod-1  | [wrangler:inf] GET /assets/xterm-LZoznX6r.css 200 OK (61ms)
app-prod-1  | [wrangler:inf] GET /assets/entry.client-FAOEGrxn.js 200 OK (25ms)
app-prod-1  | [wrangler:inf] GET /assets/components-6Yp278Dk.js 200 OK (23ms)
app-prod-1  | [wrangler:inf] GET /assets/Header-QJIkzNtL.js 200 OK (50ms)
app-prod-1  | [wrangler:inf] GET /assets/root-CFqqd5aS.js 200 OK (37ms)
app-prod-1  | [wrangler:inf] GET /assets/_index-Cuqu_AmS.js 200 OK (110ms)
app-prod-1  | [wrangler:inf] GET /logo-light-styled.png 200 OK (110ms)
app-prod-1  | [wrangler:inf] GET /logo-dark-styled.png 200 OK (110ms)
app-prod-1  | [wrangler:inf] GET /assets/wasm-CG6Dc4jp.js 200 OK (9ms)
app-prod-1  | [wrangler:inf] GET /assets/shellscript-HNM5thJl.js 200 OK (32ms)
app-prod-1  | [wrangler:inf] GET /assets/dark-plus-B74Y8nHz.js 200 OK (31ms)
app-prod-1  | [wrangler:inf] GET /assets/light-plus-w1el_4yc.js 200 OK (32ms)
app-prod-1  | [wrangler:inf] GET /favicon.svg 200 OK (16ms)
app-prod-1  | [WARN] Failed to get Ollama models:  Network connection lost.
app-prod-1  | LoadAPIKeyError [AI_LoadAPIKeyError]: Anthropic API key is missing. Pass it using the 'apiKey' parameter. Environment variables is not supported in this environment.
app-prod-1  |     at loadApiKey (file:///app/node_modules/.pnpm/@ai-sdk+provider-utils@1.0.9_zod@3.23.8/node_modules/@ai-sdk/provider-utils/src/load-api-key.ts:25:11)
app-prod-1  |     at Object.getHeaders [as headers] (file:///app/node_modules/.pnpm/@ai-sdk+anthropic@0.0.39_zod@3.23.8/node_modules/@ai-sdk/anthropic/src/anthropic-provider.ts:86:18)
app-prod-1  |     at Object.doStream (file:///app/node_modules/.pnpm/@ai-sdk+anthropic@0.0.39_zod@3.23.8/node_modules/@ai-sdk/anthropic/src/anthropic-messages-language-model.ts:220:43)
app-prod-1  |     at async fn (file:///app/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@5.4.0__svelte@5.4.0_vue@3.5.13_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:378:23)
app-prod-1  |     at null.<anonymous> (async file:///app/.wrangler/tmp/dev-cKBI5P/functionsWorker-0.5660388978709905.js:32603:22)
app-prod-1  |     at async _retryWithExponentialBackoff (file:///app/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@5.4.0__svelte@5.4.0_vue@3.5.13_typescript@5.7.2__zod@3.23.8/node_modules/ai/util/retry-with-exponential-backoff.ts:37:12) {
app-prod-1  |   cause: undefined,
app-prod-1  |   [Symbol(vercel.ai.error)]: true,
app-prod-1  |   [Symbol(vercel.ai.error.AI_LoadAPIKeyError)]: true
app-prod-1  | }
app-prod-1  | [wrangler:inf] POST /api/chat 401 Unauthorized (174ms)

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/fec81d12-8c37-4772-aabe-0f39ffeadc8b)

### Platform

macOS

**Comment by thecodacus** [comment]
for security purpose .env files are ignored during docker build.
you can either remove that from the `dockerignore` file which should make this work, or setup the api keys from UI

**Comment by thecodacus** [comment]
![image](https://github.com/user-attachments/assets/d1a70768-513f-47f2-a49c-912050be247b)

you can comment or remove these lines temporarily 
```
.env
*.local
```
