### ISSUE TITLE
The project is not starting.

### ISSUE THREAD

**Issue by Harshalkatakiya** [stackblitz-labs/bolt.diy#733]
### Describe the bug

> node pre-start.cjs  && remix vite:dev

★═══════════════════════════════════════★
          B O L T . D I Y
         ⚡️  Welcome  ⚡️
★═══════════════════════════════════════★

📍 Current Commit Version: ece0213500a94a6b29e29512c5040baf57884014
★═══════════════════════════════════════★
 warn  Route discovery/manifest behavior is changing in React Router v7
┃ You can use the `v3_lazyRouteDiscovery` future flag to opt-in early.
┃ -> https://remix.run/docs/en/2.13.1/start/future-flags#v3_lazyRouteDiscovery
┗
 warn  Data fetching is changing to a single fetch in React Router v7
┃ You can use the `v3_singleFetch` future flag to opt-in early.
┃ -> https://remix.run/docs/en/2.13.1/start/future-flags#v3_singleFetch
┗
*** Received structured exception #0xc0000005: access violation; stack: 7ffacca831f7 7ff7dee8251b 7ff7dee825e3 7ff7dee23f9c 7ff7dee23f47 7ff7de69bf5e 7ff7de69c26f 7ff7dd481ed6 7ff7de7c5e3f 7ff7de7cd0d6 7ff7de7c6343 7ff7de7cd0d6 7ff7de7c3cdc 7ff7dd471e66 7ff7dffd572f 7ffae187e8d6 7ffae2c5fbcb
MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at Miniflare2.#assembleAndUpdateConfig (D:\Projects\MERN Stack\bolt.diy\node_modules\.pnpm\miniflare@3.20241106.1\node_modules\miniflare\src\index.ts:1404:10)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at Mutex.runWith (D:\Projects\MERN Stack\bolt.diy\node_modules\.pnpm\miniflare@3.20241106.1\node_modules\miniflare\src\workers\shared\sync.ts:66:45)
    at Miniflare2.#waitForReady (D:\Projects\MERN Stack\bolt.diy\node_modules\.pnpm\miniflare@3.20241106.1\node_modules\miniflare\src\index.ts:1486:3)
    at Miniflare2._getProxyClient (D:\Projects\MERN Stack\bolt.diy\node_modules\.pnpm\miniflare@3.20241106.1\node_modules\miniflare\src\index.ts:1692:3)
    at Miniflare2.getBindings (D:\Projects\MERN Stack\bolt.diy\node_modules\.pnpm\miniflare@3.20241106.1\node_modules\miniflare\src\index.ts:1715:23)
    at getPlatformProxy (D:\Projects\MERN Stack\bolt.diy\node_modules\.pnpm\wrangler@3.91.0_@cloudflare+workers-types@4.20241127.0\node_modules\wrangler\src\api\integrations\platform\index.ts:116:24)
    at configureServer (D:\Projects\MERN Stack\bolt.diy\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_3djlhh3t6jbfog2cydlrvgreoy\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:55:11)
    at _createServer (file:///D:/Projects/MERN%20Stack/bolt.diy/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1_sass-embedded@1.81.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:63080:20)
    at configResolved (D:\Projects\MERN Stack\bolt.diy\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_3djlhh3t6jbfog2cydlrvgreoy\node_modules\@remix-run\dev\dist\vite\plugin.js:768:27)
    at async Promise.all (index 3)
    at resolveConfig (file:///D:/Projects/MERN%20Stack/bolt.diy/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1_sass-embedded@1.81.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:66404:3)
    at _createServer (file:///D:/Projects/MERN%20Stack/bolt.diy/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1_sass-embedded@1.81.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:62758:18)
    at dev (D:\Projects\MERN Stack\bolt.diy\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_3djlhh3t6jbfog2cydlrvgreoy\node_modules\@remix-run\dev\dist\vite\dev.js:39:16)
    at Object.viteDev (D:\Projects\MERN Stack\bolt.diy\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_3djlhh3t6jbfog2cydlrvgreoy\node_modules\@remix-run\dev\dist\cli\commands.js:221:3)
    at Object.run (D:\Projects\MERN Stack\bolt.diy\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_3djlhh3t6jbfog2cydlrvgreoy\node_modules\@remix-run\dev\dist\cli\run.js:271:7) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}
 ELIFECYCLE  Command failed with exit code 1.

### Link to the Bolt URL that caused the error

no link

### Steps to reproduce

pnpm install
pnpm run dev

### Expected behavior

server running on : http://localhost:5173

### Platform

- OS: Windows 11
- Browser: Chrome (stable)
- GitHub branch : stable

### Additional context

The project is not starting using the dev script. I receive this error every time. I am using Bun and the pnpm package manager.

**Comment by CCGoodman** [comment]
make sure to install the latest Microsoft Visual C++ 
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by Harshalkatakiya** [comment]
thank you so much.
it is working now.

**Comment by FLASHBiRDone** [comment]
THANK YOU!

**Comment by sammyheart213** [comment]
Thank you.

**Comment by Moodykamel17** [comment]
I installed the latest Microsoft Visual C++ and i have the same problem ????

warn  Data fetching is changing to a single fetch in React Router v7
┃ You can use the `v3_singleFetch` future flag to opt-in early.
┃ -> https://remix.run/docs/en/2.13.1/start/future-flags#v3_singleFetch
