### ISSUE TITLE
remove warnings

### ISSUE THREAD

**Issue by Harshalkatakiya** [stackblitz-labs/bolt.diy#734]
remove warnings in dev script by adding these two features in remixVitePlugin.feature :

remixVitePlugin({
        future: {
          v3_fetcherPersist: true,
          v3_relativeSplatPath: true,
          v3_throwAbortReason: true,
          v3_lazyRouteDiscovery: true,
          v3_singleFetch: true,
        },
      }),

the warnings were:

` warn  Route discovery/manifest behavior is changing in React Router v7
┃ You can use the `v3_lazyRouteDiscovery` future flag to opt-in early.
┃ -> https://remix.run/docs/en/2.13.1/start/future-flags#v3_lazyRouteDiscovery
┗
 warn  Data fetching is changing to a single fetch in React Router v7
┃ You can use the `v3_singleFetch` future flag to opt-in early.
┃ -> https://remix.run/docs/en/2.13.1/start/future-flags#v3_singleFetch
┗`

add these 2 features in vite.config.ts for remove warnings in run script.

**Comment by facilitator999** [comment]
`📍 Current Version Tag: v"0.0.5"
📍 Current Commit Version: "be7a754"
  Please wait until the URL appears here
★═══════════════════════════════════════★
Error: write EPIPE
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at __node_internal_errnoException (node:internal/errors:623:12)
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:962:11)
    at Socket._write (node:net:974:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Socket.Writable.write (node:internal/streams/writable:337:10)
    at Runtime.updateConfig (/home/bolt/public_html/node_modules/miniflare/src/runtime/index.ts:154:24)
    at Miniflare2.#assembleAndUpdateConfig (/home/bolt/public_html/node_modules/miniflare/src/index.ts:1398:28)
    at Mutex.runWith (/home/bolt/public_html/node_modules/miniflare/src/workers/shared/sync.ts:66:45)
    at Miniflare2.#waitForReady (/home/bolt/public_html/node_modules/miniflare/src/index.ts:1486:3)
    at Miniflare2._getProxyClient (/home/bolt/public_html/node_modules/miniflare/src/index.ts:1692:3)
    at Miniflare2.getBindings (/home/bolt/public_html/node_modules/miniflare/src/index.ts:1715:23)
    at getPlatformProxy (/home/bolt/public_html/node_modules/wrangler/wrangler-dist/cli.js:180408:20)
    at configureServer (/home/bolt/public_html/node_modules/@remix-run/dev/dist/vite/cloudflare-proxy-plugin.js:55:11)
    at _createServer (file:///home/bolt/public_html/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:63080:20)
    at configResolved (/home/bolt/public_html/node_modules/@remix-run/dev/dist/vite/plugin.js:768:27)
    at async Promise.all (index 3)
    at resolveConfig (file:///home/bolt/public_html/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:66404:3)
    at _createServer (file:///home/bolt/public_html/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:62758:18)
    at dev (/home/bolt/public_html/node_modules/@remix-run/dev/dist/vite/dev.js:39:16)
    at Object.viteDev (/home/bolt/public_html/node_modules/@remix-run/dev/dist/cli/commands.js:221:3)
    at Object.run (/home/bolt/public_html/node_modules/@remix-run/dev/dist/cli/run.js:271:7) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}`
