### ISSUE TITLE
APICallError (not found) with local Ollama 3.2 usage

### ISSUE THREAD

**Issue by toniritter** [stackblitz-labs/bolt.diy#736]
### Describe the bug

Currently, i cant use the bolt.diy hence an error within the API call to OLLama is raised.

`
APICallError [AI_APICallError]: Not Found
    at C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\ollama-ai-provider\node_modules\@ai-sdk\provider-utils\src\response-handler.ts:72:16
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at postToApi (C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\ollama-ai-provider\node_modules\@ai-sdk\provider-utils\src\post-to-api.ts:81:28)
    at OllamaChatLanguageModel.doStream (C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\ollama-ai-provider\src\ollama-chat-language-model.ts:230:50)
    at fn (file:///C:/Users/ToniR/Projekte/bolt.diy/bolt.diy/node_modules/ai/core/generate-text/stream-text.ts:378:23)
    at file:///C:/Users/ToniR/Projekte/bolt.diy/bolt.diy/node_modules/ai/core/telemetry/record-span.ts:18:22
    at _retryWithExponentialBackoff (file:///C:/Users/ToniR/Projekte/bolt.diy/bolt.diy/node_modules/ai/util/retry-with-exponential-backoff.ts:37:12)
    at startStep (file:///C:/Users/ToniR/Projekte/bolt.diy/bolt.diy/node_modules/ai/core/generate-text/stream-text.ts:333:13)
    at fn (file:///C:/Users/ToniR/Projekte/bolt.diy/bolt.diy/node_modules/ai/core/generate-text/stream-text.ts:414:11)
    at file:///C:/Users/ToniR/Projekte/bolt.diy/bolt.diy/node_modules/ai/core/telemetry/record-span.ts:18:22
    at chatAction (C:/Users/ToniR/Projekte/bolt.diy/bolt.diy/app/routes/api.chat.ts:66:20)
    at Object.callRouteAction (C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\@remix-run\server-runtime\dist\data.js:36:16)
    at C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\@remix-run\router\router.ts:4899:19
    at callLoaderOrAction (C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\@remix-run\router\router.ts:4963:16)
    at async Promise.all (index 0)
    at defaultDataStrategy (C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\@remix-run\router\router.ts:4772:17)
    at callDataStrategyImpl (C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\@remix-run\router\router.ts:4835:17)
    at callDataStrategy (C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\@remix-run\router\router.ts:3992:19)
    at submit (C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\@remix-run\router\router.ts:3755:21)
    at queryImpl (C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\@remix-run\router\router.ts:3684:22)
    at Object.queryRoute (C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\@remix-run\router\router.ts:3629:18)
    at handleResourceRequest (C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\@remix-run\server-runtime\dist\server.js:402:20)
    at requestHandler (C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\@remix-run\server-runtime\dist\server.js:156:18)
    at C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:70:25 {
  cause: undefined,
  url: 'http://127.0.0.1:11434/api/chat',
  requestBodyValues: {
    format: undefined,
    model: 'claude-3-5-sonnet-latest',
    options: { num_ctx: 8192, num_predict: 8000, temperature: 0 },
    messages: [ [Object], [Object] ],
    tools: undefined
  },
  statusCode: 404,
  responseHeaders: {
    'content-length': '78',
    'content-type': 'application/json; charset=utf-8',
    date: 'Sun, 15 Dec 2024 11:34:40 GMT'
  },
  url: 'http://127.0.0.1:11434/api/chat',
  requestBodyValues: {
    format: undefined,
    model: 'claude-3-5-sonnet-latest',
    options: { num_ctx: 8192, num_predict: 8000, temperature: 0 },
    messages: [ [Object], [Object] ],
    tools: undefined
  },
  statusCode: 404,
  responseHeaders: {
    'content-length': '78',
    'content-type': 'application/json; charset=utf-8',
    date: 'Sun, 15 Dec 2024 11:34:40 GMT'
  url: 'http://127.0.0.1:11434/api/chat',
  requestBodyValues: {
    format: undefined,
    model: 'claude-3-5-sonnet-latest',
    options: { num_ctx: 8192, num_predict: 8000, temperature: 0 },
    messages: [ [Object], [Object] ],
    tools: undefined
  },
  statusCode: 404,
  responseHeaders: {
  url: 'http://127.0.0.1:11434/api/chat',
  requestBodyValues: {
    format: undefined,
    model: 'claude-3-5-sonnet-latest',
    options: { num_ctx: 8192, num_predict: 8000, temperature: 0 },
    messages: [ [Object], [Object] ],
    tools: undefined
  },
  statusCode: 404,
  url: 'http://127.0.0.1:11434/api/chat',
  requestBodyValues: {
    format: undefined,
    model: 'claude-3-5-sonnet-latest',
    options: { num_ctx: 8192, num_predict: 8000, temperature: 0 },
    messages: [ [Object], [Object] ],
  url: 'http://127.0.0.1:11434/api/chat',
  requestBodyValues: {
    format: undefined,
    model: 'claude-3-5-sonnet-latest',
  url: 'http://127.0.0.1:11434/api/chat',
  requestBodyValues: {
    format: undefined,
  url: 'http://127.0.0.1:11434/api/chat',
  requestBodyValues: {
  url: 'http://127.0.0.1:11434/api/chat',
  requestBodyValues: {
    format: undefined,
  url: 'http://127.0.0.1:11434/api/chat',
  requestBodyValues: {
  url: 'http://127.0.0.1:11434/api/chat',
  url: 'http://127.0.0.1:11434/api/chat',
  url: 'http://127.0.0.1:11434/api/chat',
  requestBodyValues: {
  url: 'http://127.0.0.1:11434/api/chat',
  requestBodyValues: {
    format: undefined,
  requestBodyValues: {
    format: undefined,
    format: undefined,
    model: 'claude-3-5-sonnet-latest',
    model: 'claude-3-5-sonnet-latest',
    options: { num_ctx: 8192, num_predict: 8000, temperature: 0 },
    options: { num_ctx: 8192, num_predict: 8000, temperature: 0 },
    messages: [ [Object], [Object] ],
    messages: [ [Object], [Object] ],
    tools: undefined
  },
  statusCode: 404,
  responseHeaders: {
    'content-length': '78',
    'content-type': 'application/json; charset=utf-8',
    date: 'Sun, 15 Dec 2024 11:34:40 GMT'
  },
  responseBody: '{"error":"model \\"claude-3-5-sonnet-latest\\" not found, try pulling it first"}',
  isRetryable: false,
  data: undefined,
  [Symbol(vercel.ai.error)]: true,
  [Symbol(vercel.ai.error.AI_APICallError)]: true
}
`

### Link to the Bolt URL that caused the error

https://github.com/stackblitz-labs/bolt.diy/tree/stable

### Steps to reproduce

1. setup .env.local properly
`OLLAMA_API_BASE_URL=http://127.0.0.1:11434`
2. start npm run dev

### Expected behavior

The OLLAMA Model 3.2 can be used

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/066ce58b-59d8-4ef2-8256-8979eb39c3ce)

### Platform

* Windows 11
* stable branch
* Node.js v22.12.0

### Additional context

![image](https://github.com/user-attachments/assets/5a386c1c-c17b-4b58-969d-6a98a31a706a)

**Comment by matichek** [comment]
ya, I have the same

**Comment by Harshalkatakiya** [comment]
yes, I have the same issue

**Comment by matichek** [comment]
> ### Describe the bug
> Currently, i cant use the bolt.diy hence an error within the API call to OLLama is raised.
> 
> `APICallError [AI_APICallError]: Not Found at C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\ollama-ai-provider\node_modules\@ai-sdk\provider-utils\src\response-handler.ts:72:16 at processTicksAndRejections (node:internal/process/task_queues:105:5) at postToApi (C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\ollama-ai-provider\node_modules\@ai-sdk\provider-utils\src\post-to-api.ts:81:28) at OllamaChatLanguageModel.doStream (C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\ollama-ai-provider\src\ollama-chat-language-model.ts:230:50) at fn (file:///C:/Users/ToniR/Projekte/bolt.diy/bolt.diy/node_modules/ai/core/generate-text/stream-text.ts:378:23) at file:///C:/Users/ToniR/Projekte/bolt.diy/bolt.diy/node_modules/ai/core/telemetry/record-span.ts:18:22 at _retryWithExponentialBackoff (file:///C:/Users/ToniR/Projekte/bolt.diy/bolt.diy/node_modules/ai/util/retry-with-exponential-backoff.ts:37:12) at startStep (file:///C:/Users/ToniR/Projekte/bolt.diy/bolt.diy/node_modules/ai/core/generate-text/stream-text.ts:333:13) at fn (file:///C:/Users/ToniR/Projekte/bolt.diy/bolt.diy/node_modules/ai/core/generate-text/stream-text.ts:414:11) at file:///C:/Users/ToniR/Projekte/bolt.diy/bolt.diy/node_modules/ai/core/telemetry/record-span.ts:18:22 at chatAction (C:/Users/ToniR/Projekte/bolt.diy/bolt.diy/app/routes/api.chat.ts:66:20) at Object.callRouteAction (C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\@remix-run\server-runtime\dist\data.js:36:16) at C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\@remix-run\router\router.ts:4899:19 at callLoaderOrAction (C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\@remix-run\router\router.ts:4963:16) at async Promise.all (index 0) at defaultDataStrategy (C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\@remix-run\router\router.ts:4772:17) at callDataStrategyImpl (C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\@remix-run\router\router.ts:4835:17) at callDataStrategy (C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\@remix-run\router\router.ts:3992:19) at submit (C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\@remix-run\router\router.ts:3755:21) at queryImpl (C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\@remix-run\router\router.ts:3684:22) at Object.queryRoute (C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\@remix-run\router\router.ts:3629:18) at handleResourceRequest (C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\@remix-run\server-runtime\dist\server.js:402:20) at requestHandler (C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\@remix-run\server-runtime\dist\server.js:156:18) at C:\Users\ToniR\Projekte\bolt.diy\bolt.diy\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:70:25 { cause: undefined, url: 'http://127.0.0.1:11434/api/chat', requestBodyValues: { format: undefined, model: 'claude-3-5-sonnet-latest', options: { num_ctx: 8192, num_predict: 8000, temperature: 0 }, messages: [ [Object], [Object] ], tools: undefined }, statusCode: 404, responseHeaders: { 'content-length': '78', 'content-type': 'application/json; charset=utf-8', date: 'Sun, 15 Dec 2024 11:34:40 GMT' }, url: 'http://127.0.0.1:11434/api/chat', requestBodyValues: { format: undefined, model: 'claude-3-5-sonnet-latest', options: { num_ctx: 8192, num_predict: 8000, temperature: 0 }, messages: [ [Object], [Object] ], tools: undefined }, statusCode: 404, responseHeaders: { 'content-length': '78', 'content-type': 'application/json; charset=utf-8', date: 'Sun, 15 Dec 2024 11:34:40 GMT' url: 'http://127.0.0.1:11434/api/chat', requestBodyValues: { format: undefined, model: 'claude-3-5-sonnet-latest', options: { num_ctx: 8192, num_predict: 8000, temperature: 0 }, messages: [ [Object], [Object] ], tools: undefined }, statusCode: 404, responseHeaders: { url: 'http://127.0.0.1:11434/api/chat', requestBodyValues: { format: undefined, model: 'claude-3-5-sonnet-latest', options: { num_ctx: 8192, num_predict: 8000, temperature: 0 }, messages: [ [Object], [Object] ], tools: undefined }, statusCode: 404, url: 'http://127.0.0.1:11434/api/chat', requestBodyValues: { format: undefined, model: 'claude-3-5-sonnet-latest', options: { num_ctx: 8192, num_predict: 8000, temperature: 0 }, messages: [ [Object], [Object] ], url: 'http://127.0.0.1:11434/api/chat', requestBodyValues: { format: undefined, model: 'claude-3-5-sonnet-latest', url: 'http://127.0.0.1:11434/api/chat', requestBodyValues: { format: undefined, url: 'http://127.0.0.1:11434/api/chat', requestBodyValues: { url: 'http://127.0.0.1:11434/api/chat', requestBodyValues: { format: undefined, url: 'http://127.0.0.1:11434/api/chat', requestBodyValues: { url: 'http://127.0.0.1:11434/api/chat', url: 'http://127.0.0.1:11434/api/chat', url: 'http://127.0.0.1:11434/api/chat', requestBodyValues: { url: 'http://127.0.0.1:11434/api/chat', requestBodyValues: { format: undefined, requestBodyValues: { format: undefined, format: undefined, model: 'claude-3-5-sonnet-latest', model: 'claude-3-5-sonnet-latest', options: { num_ctx: 8192, num_predict: 8000, temperature: 0 }, options: { num_ctx: 8192, num_predict: 8000, temperature: 0 }, messages: [ [Object], [Object] ], messages: [ [Object], [Object] ], tools: undefined }, statusCode: 404, responseHeaders: { 'content-length': '78', 'content-type': 'application/json; charset=utf-8', date: 'Sun, 15 Dec 2024 11:34:40 GMT' }, responseBody: '{"error":"model \\"claude-3-5-sonnet-latest\\" not found, try pulling it first"}', isRetryable: false, data: undefined, [Symbol(vercel.ai.error)]: true, [Symbol(vercel.ai.error.AI_APICallError)]: true }`
> 
> ### Link to the Bolt URL that caused the error
> https://github.com/stackblitz-labs/bolt.diy/tree/stable
> 
> ### Steps to reproduce
> 1. setup .env.local properly
>    `OLLAMA_API_BASE_URL=http://127.0.0.1:11434`
> 2. start npm run dev
> 
> ### Expected behavior
> The OLLAMA Model 3.2 can be used
> 
> ### Screen Recording / Screenshot
> ![image](https://private-user-images.githubusercontent.com/31060373/395859458-066ce58b-59d8-4ef2-8256-8979eb39c3ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyODU4NTAsIm5iZiI6MTczNDI4NTU1MCwicGF0aCI6Ii8zMTA2MDM3My8zOTU4NTk0NTgtMDY2Y2U1OGItNTlkOC00ZWYyLTgyNTYtODk3OWViMzljM2NlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE1VDE3NTkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNGRhMDBjZGU3NjY0OTI1YzBjMjY0MDA0NjRkZTk1ZjczODk3NmZjNzRlNmQ0MTc0ODY3NGViN2NkZjYzYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1IxzbQLIvRH_AaDkZERK7MHlm__-NjvzV8b21GvqPc8)
> 
> ### Platform
> * Windows 11
> * stable branch
> * Node.js v22.12.0
> 
> ### Provider Used
> _No response_
> 
> ### Model Used
> _No response_
> 
> ### Additional context
> ![image](https://private-user-images.githubusercontent.com/31060373/395859487-5a386c1c-c17b-4b58-969d-6a98a31a706a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyODU4NTAsIm5iZiI6MTczNDI4NTU1MCwicGF0aCI6Ii8zMTA2MDM3My8zOTU4NTk0ODctNWEzODZjMWMtYzE3Yi00YjU4LTk2OWQtNmE5OGEzMWE3MDZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE1VDE3NTkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNDE2YmJmNDBkMzE3YzJlMGRhYTY4ZmY3YTgzNTU0YjMwMmZhZTJiNjg1ZWY4NmEwY2Q3NzZhOTgxYTE3ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qYeWWGH71jRV_P5kYFBcQWMPKlm6v0PmzfOgx9pTbG4)

maybe we have to run "ollama server"?

**Comment by Shubhk0** [comment]
yes, I have the same issue

**Comment by toniritter** [comment]
any news here?

**Comment by leex279** [comment]
Closed for know: If still a problem, open a topic in community please to investigate deeper: https://thinktank.ottomator.ai/c/bolt-diy/bolt-diy-issues-and-troubleshooting/22

---

Windows => use PNPM instead of NPM as described in the docs (https://stackblitz-labs.github.io/bolt.diy/)
