### ISSUE TITLE
Cannot start Bolt

### ISSUE THREAD

**Issue by vklonis** [stackblitz-labs/bolt.diy#775]
### Describe the bug

under windows, i have git and pmpm. I run the pnpm install succefully but when i try to run pnpm run dev afterwards i get the below error. I have checked file and folders permisions and tried a fresh install but keep getting stuck on the same place every time. Any help would be appreciated. 

PS C:\projects\ottoDev\bolt.diy> pnpm run dev

> bolt@0.0.1 dev C:\projects\ottoDev\bolt.diy
> node pre-start.cjs  && remix vite:dev

★═══════════════════════════════════════★
          B O L T . D I Y
         ⚡️  Welcome  ⚡️
★═══════════════════════════════════════★

📍 Current Commit Version: 27fcd03db6e7d42d36ffb409e263857f4b05e063
★═══════════════════════════════════════★
 warn  Route discovery/manifest behavior is changing in React Router v7
┃ You can use the `v3_lazyRouteDiscovery` future flag to opt-in early.
┃ -> https://remix.run/docs/en/2.13.1/start/future-flags#v3_lazyRouteDiscovery
┗
 warn  Data fetching is changing to a single fetch in React Router v7
┃ You can use the `v3_singleFetch` future flag to opt-in early.
┃ -> https://remix.run/docs/en/2.13.1/start/future-flags#v3_singleFetch
┗
*** Received structured exception #0xc0000005: access violation; stack: 7ffc596f301f 7ff76564aa5a 7ff76564ab23 7ff7655ec4ac 7ff7655ec457 7ff764e5143e 7ff764e5174f 7ff763c61ed6 7ff764f7bcef 7ff764f82f86 7ff764f7c1f3 7ff764f82f86 7ff764f79b8c 7ff763c51e66 7ff7667b961f 7ffc67a67373 7ffc693fcc90MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at Miniflare2.#assembleAndUpdateConfig (C:\projects\ottoDev\bolt.diy\node_modules\.pnpm\miniflare@3.20241205.0\node_modules\miniflare\src\index.ts:1404:10)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at Mutex.runWith (C:\projects\ottoDev\bolt.diy\node_modules\.pnpm\miniflare@3.20241205.0\node_modules\miniflare\src\workers\shared\sync.ts:66:45)
    at Miniflare2.#waitForReady (C:\projects\ottoDev\bolt.diy\node_modules\.pnpm\miniflare@3.20241205.0\node_modules\miniflare\src\index.ts:1486:3)
    at Miniflare2._getProxyClient (C:\projects\ottoDev\bolt.diy\node_modules\.pnpm\miniflare@3.20241205.0\node_modules\miniflare\src\index.ts:1692:3)
    at Miniflare2.getBindings (C:\projects\ottoDev\bolt.diy\node_modules\.pnpm\miniflare@3.20241205.0\node_modules\miniflare\src\index.ts:1715:23)
    at getPlatformProxy (C:\projects\ottoDev\bolt.diy\node_modules\.pnpm\wrangler@3.96.0_@cloudflare+workers-types@4.20241216.0\node_modules\wrangler\src\api\integrations\platform\index.ts:126:24)
    at configureServer (C:\projects\ottoDev\bolt.diy\node_modules\.pnpm\@remix-run+dev@2.15.1_@remix-run+react@2.15.1_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_ttmexdiqjs5zfprfdkfcvtqw5e\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:55:11)
    at _createServer (file:///C:/projects/ottoDev/bolt.diy/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.2_sass-embedded@1.83.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:63080:20)
    at configResolved (C:\projects\ottoDev\bolt.diy\node_modules\.pnpm\@remix-run+dev@2.15.1_@remix-run+react@2.15.1_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_ttmexdiqjs5zfprfdkfcvtqw5e\node_modules\@remix-run\dev\dist\vite\plugin.js:768:27)
    at async Promise.all (index 3)
    at resolveConfig (file:///C:/projects/ottoDev/bolt.diy/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.2_sass-embedded@1.83.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:66404:3)
    at _createServer (file:///C:/projects/ottoDev/bolt.diy/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.2_sass-embedded@1.83.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:62758:18)
    at dev (C:\projects\ottoDev\bolt.diy\node_modules\.pnpm\@remix-run+dev@2.15.1_@remix-run+react@2.15.1_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_ttmexdiqjs5zfprfdkfcvtqw5e\node_modules\@remix-run\dev\dist\vite\dev.js:39:16)
    at Object.viteDev (C:\projects\ottoDev\bolt.diy\node_modules\.pnpm\@remix-run+dev@2.15.1_@remix-run+react@2.15.1_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_ttmexdiqjs5zfprfdkfcvtqw5e\node_modules\@remix-run\dev\dist\cli\commands.js:221:3)
    at Object.run (C:\projects\ottoDev\bolt.diy\node_modules\.pnpm\@remix-run+dev@2.15.1_@remix-run+react@2.15.1_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_ttmexdiqjs5zfprfdkfcvtqw5e\node_modules\@remix-run\dev\dist\cli\run.js:271:7) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}
 ELIFECYCLE  Command failed with exit code 1.
PS C:\projects\ottoDev\bolt.diy> 

### Link to the Bolt URL that caused the error

no project yet

### Steps to reproduce

1. clean install in an empty folder with git clone https://github.com/stackblitz-labs/bolt.diy.git
2. pnpm install
3. pnpm run dev

### Expected behavior

run the app , give me the local url to access similarly to bolt.new

### Platform

- Windows 10
- MS Edge

**Comment by cossil** [comment]
Similar here:
PS C:\ai\bolt.diy> pnpm run dev

> bolt@0.0.2 dev C:\ai\bolt.diy
> node pre-start.cjs  && remix vite:dev


★═══════════════════════════════════════★
          B O L T . D I Y
         ⚡️  Welcome  ⚡️
★═══════════════════════════════════════★

📍 Current Commit Version: 89eac1ba8b2ada92dd76da9671d17e08de61a8bf
★═══════════════════════════════════════★
 warn  Data fetching is changing to a single fetch in React Router v7
┃ You can use the `v3_singleFetch` future flag to opt-in early.
┃ -> https://remix.run/docs/en/2.13.1/start/future-flags#v3_singleFetch
┗
*** Received structured exception #0xc0000005: access violation; stack: 7fffe559301f 7ff66273251b 7ff6627325e3 7ff6626d3f9c 7ff6626d3f47 7ff661f4bf5e 7ff661f4c26f 7ff660d31ed6 7ff662075e3f 7ff66207d0d6 7ff662076343 7ff66207d0d6 7ff662073cdc 7ff660d21e66 7ff66388572f 7ff80483257c 7ff805e6af07
MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at Miniflare2.#assembleAndUpdateConfig (C:\ai\bolt.diy\node_modules\.pnpm\miniflare@3.20241106.1\node_modules\miniflare\src\index.ts:1404:10)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at Mutex.runWith (C:\ai\bolt.diy\node_modules\.pnpm\miniflare@3.20241106.1\node_modules\miniflare\src\workers\shared\sync.ts:66:45)
    at Miniflare2.#waitForReady (C:\ai\bolt.diy\node_modules\.pnpm\miniflare@3.20241106.1\node_modules\miniflare\src\index.ts:1486:3)
    at Miniflare2._getProxyClient (C:\ai\bolt.diy\node_modules\.pnpm\miniflare@3.20241106.1\node_modules\miniflare\src\index.ts:1692:3)
    at Miniflare2.getBindings (C:\ai\bolt.diy\node_modules\.pnpm\miniflare@3.20241106.1\node_modules\miniflare\src\index.ts:1715:23)
    at getPlatformProxy (C:\ai\bolt.diy\node_modules\.pnpm\wrangler@3.91.0_@cloudflare+workers-types@4.20241127.0\node_modules\wrangler\src\api\integrations\platform\index.ts:116:24)
    at configureServer (C:\Ai\bolt.diy\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_3djlhh3t6jbfog2cydlrvgreoy\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:55:11)
    at _createServer (file:///C:/ai/bolt.diy/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1_sass-embedded@1.81.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:63080:20)
    at configResolved (C:\ai\bolt.diy\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_3djlhh3t6jbfog2cydlrvgreoy\node_modules\@remix-run\dev\dist\vite\plugin.js:768:27)
    at async Promise.all (index 3)
    at resolveConfig (file:///C:/ai/bolt.diy/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1_sass-embedded@1.81.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:66404:3)
    at _createServer (file:///C:/ai/bolt.diy/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1_sass-embedded@1.81.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:62758:18)
    at dev (C:\ai\bolt.diy\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_3djlhh3t6jbfog2cydlrvgreoy\node_modules\@remix-run\dev\dist\vite\dev.js:39:16)
    at Object.viteDev (C:\ai\bolt.diy\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_3djlhh3t6jbfog2cydlrvgreoy\node_modules\@remix-run\dev\dist\cli\commands.js:221:3)
    at Object.run (C:\ai\bolt.diy\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_3djlhh3t6jbfog2cydlrvgreoy\node_modules\@remix-run\dev\dist\cli\run.js:271:7) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}
 ELIFECYCLE  Command failed with exit code 1.
PS C:\ai\bolt.diy>

**Comment by BArtistically** [comment]
It's a problem with wranger, I think. Until it's fixed I always do:
pnpm uninstall wrangler
pnpm install wrangler@3.57.1 
after a git pull
Version 3.57.1 seems to work still.

**Comment by vklonis** [comment]
> It's a problem with wranger, I think. Until it's fixed I always do: pnpm uninstall wrangler pnpm install wrangler@3.57.1 after a git pull Version 3.57.1 seems to work still.

thanks so much. this fixed it for me

**Comment by leex279** [comment]
Mostly it is more a problem with not installed latest MS Redis C++

Check help videos/content: https://thinktank.ottomator.ai/t/videos-tutorial-helpful-content/3243/1

See FAQ: https://stackblitz-labs.github.io/bolt.diy/FAQ/#troubleshooting
