### ISSUE TITLE
fetch failed

### ISSUE THREAD

**Issue by EventExecutor** [stackblitz-labs/bolt.diy#777]
### Describe the bug

I followed the whole tutorial with the same commands and procedures, but it gives me this error:
"WARN Constants Failed to get Ollama models: fetch failed"
And i don't know why.

### Link to the Bolt URL that caused the error

http://localhost:5173/chat/2

### Steps to reproduce

As I said I followed the whole tutorial, started the .bat at the end, but it doesn't work

### Expected behavior

I followed the whole tutorial with the same commands and procedures, but it gives me this error:
"WARN Constants Failed to get Ollama models: fetch failed"
And i don't know why.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/ae84643e-3b9d-4dc2-9246-46794b8b60ce)

### Platform

- OS: Windows 11
- Browser: Chrome
- Version: of what?

**Comment by roodfps** [comment]
up

**Comment by thecodacus** [comment]
these are not errors, if you set the ollama baseUrl in the settings tab it should be working. 
please try that and see, if not working please give us more detail on how you have setup both the system

**Comment by EventExecutor** [comment]
How can i do it?

**Comment by thecodacus** [comment]
![Screenshot 2024-12-17 at 7 33 14 PM](https://github.com/user-attachments/assets/5e4aad8d-24c0-4789-8d91-5579bba4c46f)

**Comment by EventExecutor** [comment]
Ok, found it

**Comment by EventExecutor** [comment]
But which one should I put? the localhost?

**Comment by thecodacus** [comment]
are you trying to use ollama models?

**Comment by EventExecutor** [comment]
Like this:
![image](https://github.com/user-attachments/assets/c76fd0aa-666e-43d5-a2af-8d2c200f1fcc)

**Comment by thecodacus** [comment]
> are you trying to use ollama models?

if not then you don't need to pay attention to this message as this is just an warning only

**Comment by EventExecutor** [comment]
Then what should I do, I put the link base url, but it still doesn't work, what is it I have to save or do something else? because there is no save button

**Comment by EventExecutor** [comment]
Error: No route matches URL "/tags"
    at getInternalRouterError (C:\Users\T3ddyPro\Desktop\OTTODEV\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:5505:5)
    at Object.query (C:\Users\T3ddyPro\Desktop\OTTODEV\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3527:19)
    at handleDocumentRequest (C:\Users\T3ddyPro\Desktop\OTTODEV\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:275:35)
    at requestHandler (C:\Users\T3ddyPro\Desktop\OTTODEV\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:160:24)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at C:\Users\T3ddyPro\Desktop\OTTODEV\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_3djlhh3t6jbfog2cydlrvgreoy\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:70:25
WARN Constants Failed to get Ollama models:  fetch failed
No routes matched location "/tags"
ErrorResponseImpl {
  status: 404,
  statusText: 'Not Found',
  internal: true,
  data: 'Error: No route matches URL "/tags"',
  error: Error: No route matches URL "/tags"
      at getInternalRouterError (C:\Users\T3ddyPro\Desktop\OTTODEV\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:5505:5)
      at Object.query (C:\Users\T3ddyPro\Desktop\OTTODEV\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3527:19)
      at handleDocumentRequest (C:\Users\T3ddyPro\Desktop\OTTODEV\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:275:35)
      at requestHandler (C:\Users\T3ddyPro\Desktop\OTTODEV\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:160:24)
      at processTicksAndRejections (node:internal/process/task_queues:105:5)
      at C:\Users\T3ddyPro\Desktop\OTTODEV\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_3djlhh3t6jbfog2cydlrvgreoy\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:70:25
}
No routes matched location "/tags"
Error: No route matches URL "/tags"
    at getInternalRouterError (C:\Users\T3ddyPro\Desktop\OTTODEV\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:5505:5)
    at Object.query (C:\Users\T3ddyPro\Desktop\OTTODEV\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3527:19)
    at handleDocumentRequest (C:\Users\T3ddyPro\Desktop\OTTODEV\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:275:35)
    at requestHandler (C:\Users\T3ddyPro\Desktop\OTTODEV\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:160:24)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at C:\Users\T3ddyPro\Desktop\OTTODEV\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_3djlhh3t6jbfog2cydlrvgreoy\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:70:25
WARN Constants Failed to get Ollama models:  fetch failed
No routes matched location "/tags"
ErrorResponseImpl {
  status: 404,
  statusText: 'Not Found',
  internal: true,
  data: 'Error: No route matches URL "/tags"',
  error: Error: No route matches URL "/tags"
      at getInternalRouterError (C:\Users\T3ddyPro\Desktop\OTTODEV\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:5505:5)
      at Object.query (C:\Users\T3ddyPro\Desktop\OTTODEV\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3527:19)
      at handleDocumentRequest (C:\Users\T3ddyPro\Desktop\OTTODEV\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:275:35)
      at requestHandler (C:\Users\T3ddyPro\Desktop\OTTODEV\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:160:24)
      at processTicksAndRejections (node:internal/process/task_queues:105:5)
      at C:\Users\T3ddyPro\Desktop\OTTODEV\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_3djlhh3t6jbfog2cydlrvgreoy\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:70:25
}
No routes matched location "/tags"

wtf is this???

**Comment by EventExecutor** [comment]
Are you there?

**Comment by EventExecutor** [comment]
As a provider I use iliad, for what I use of model, I use Ollama, otherwise I didn't have this problem

**Comment by EventExecutor** [comment]
Are you there?

**Comment by thecodacus** [comment]
if you need to use Ollama use then please put the ollama url in the settings. else its not required.

**Comment by EventExecutor** [comment]
What do you mean the ollama url? do you mean the base url?
If so I've already tried it and it still doesn't work

**Comment by thecodacus** [comment]
http://localhost:5173 is not base url for ollama its base url for bolt
is ollama running in your local machine or its running in docker

**Comment by EventExecutor** [comment]
In my local machine

**Comment by thecodacus** [comment]
use `http://127.0.0.1:11434` as the base url for ollama

**Comment by EventExecutor** [comment]
i try

**Comment by EventExecutor** [comment]
Not working, same message "WARN Constants Failed to get Ollama models:  fetch failed", but do I have to put that url in bolt settings in the base url of ollama? or what?

**Comment by thecodacus** [comment]
yes

**Comment by EventExecutor** [comment]
Then it doesn't work

**Comment by thecodacus** [comment]
are you able to run ollama on terminal?

**Comment by Soumyaranjan-17** [comment]
Yes I have also this same problem 
yes I am able to run ollama model in terminal
i have described it here https://github.com/stackblitz-labs/bolt.diy/issues/874
![image](https://github.com/user-attachments/assets/6445e6fb-0562-40f9-9e34-ce42bbad4535)
![image](https://github.com/user-attachments/assets/f095e0b1-cee6-45d4-a93e-64b983828a7d)

**Comment by Soumyaranjan-17** [comment]
**SET in .env**
```
OLLAMA_API_BASE_URL=http://127.0.0.1:11434
```

don't set 

> OLLAMA_API_BASE_URL=http://localhost:11434
it is wrong due to some IPV6 problem 

and in UI that input field should be clear otherwise it will override the .env

![image](https://github.com/user-attachments/assets/32d00a23-786d-4a49-95e4-ebf3254f1a66)

**Comment by leex279** [comment]
Closed for know: If still a problem, open a topic in community please to investigate deeper: https://thinktank.ottomator.ai/c/bolt-diy/bolt-diy-issues-and-troubleshooting/22
