### ISSUE TITLE
Cant use openwebui api.

### ISSUE THREAD

**Issue by wangyuc** [stackblitz-labs/bolt.diy#786]
### Describe the bug

OPENAI_LIKE_API_BASE_URL=http://10.231.20.101:17000/api/chat/completions
or
OPENAI_LIKE_API_BASE_URL=http://10.231.20.101:17000/api/
console error:

WARN Constants Failed to get Ollama models:  fetch failed
Error getting OpenAILike models: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:5584:19)
    at successSteps (node:internal/deps/undici/undici:5555:27)
    at fullyReadBody (node:internal/deps/undici/undici:1665:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at specConsumeBody (node:internal/deps/undici/undici:5564:7)
    at Object.getOpenAILikeModels [as getDynamicModels] (D:/DevCode/WebDev/bolt.diy-0.0.2/app/utils/constants.ts:427:17)
    at async Promise.all (index 1)
    at Module.initializeModelList (D:/DevCode/WebDev/bolt.diy-0.0.2/app/utils/constants.ts:483:9)
    at handleRequest (D:/DevCode/WebDev/bolt.diy-0.0.2/app/entry.server.tsx:30:3)
    at handleDocumentRequest (D:\DevCode\WebDev\bolt.diy-0.0.2\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:340:12)
    at requestHandler (D:\DevCode\WebDev\bolt.diy-0.0.2\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:160:18)
    at D:\DevCode\WebDev\bolt.diy-0.0.2\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_3djlhh3t6jbfog2cydlrvgreoy\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:70:25
TypeError: fetch failed
    at node:internal/deps/undici/undici:12618:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.getOpenRouterModels [as getDynamicModels] (D:\DevCode\WebDev\bolt.diy-0.0.2\app\utils\constants.ts:470:5)
    at async Promise.all (index 2)
    at Module.initializeModelList (D:\DevCode\WebDev\bolt.diy-0.0.2\app\utils\constants.ts:525:7)
    at handleRequest (D:/DevCode/WebDev/bolt.diy-0.0.2/app/entry.server.tsx:30:3)
    at handleDocumentRequest (D:\DevCode\WebDev\bolt.diy-0.0.2\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:340:12)
    at requestHandler (D:\DevCode\WebDev\bolt.diy-0.0.2\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:160:18)
    at D:\DevCode\WebDev\bolt.diy-0.0.2\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_3djlhh3t6jbfog2cydlrvgreoy\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:70:25 {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:7760:28)
      at node:internal/deps/undici/undici:7716:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:7746:37)
      at processImmediate (node:internal/timers:476:21)
      at process.topLevelDomainCallback (node:domain:161:15)
      at process.callbackTrampoline (node:internal/async_hooks:126:24) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}

### Link to the Bolt URL that caused the error

http://127.0.0.1:5173

### Steps to reproduce

1..env.local  :OPENAI_LIKE_API_BASE_URL=http://10.231.20.101:17000/api/chat/completions
2. .env.local  OPENAI_LIKE_API_KEY=xxxx
3.pnpm run dev

### Expected behavior

Normal running 。

### Platform

- OS: [ Windows11]
- Browser: [Edge]
- Version: [0.0.2]

**Comment by dustinwloring1988** [comment]
this might be a good provider to add, ill look into it when I have a change unless someone beats me to it.

**Comment by leex279** [comment]
@dustinwloring1988 did you look into it? :)

**Comment by vishalkrv** [comment]
I tried using Open WebUI and it worked.

1. Update .env.local file
2. Set the env OPENAI_LIKE_API_BASE_URL=http://<IP_ADDRESS>/api
3. Set the env OPENAI_LIKE_API_KEY=<API_KEY>
4. Once the bolt.diy UI is up, select the OpenAILike option from the dropdown

<img width="629" alt="Image" src="https://github.com/user-attachments/assets/f79ceed0-e1c2-40b1-8fba-41cddd35cba5" />

**Comment by xKevIsDev** [comment]
Is this still and ongoing issue? Cant seem to replicate. 

Can we close this now?
