### ISSUE TITLE
ERROR Chat Request failed  Error: An error occurred.

### ISSUE THREAD

**Issue by mredodos** [stackblitz-labs/bolt.diy#820]
### Describe the bug

i can start or continue a chat, my message is like not sent or not receive answer from provider

![image](https://github.com/user-attachments/assets/4dc2ef25-ab9c-40a8-9776-b58eb72aad12)

### Link to the Bolt URL that caused the error

http://localhost:5173/

### Steps to reproduce

open bolt
write in the new chat or old chat

### Expected behavior

im expected all works..

### Platform

- docker
- last stable version

### Provider Used

all

### Model Used

all

**Comment by rezasmind** [comment]
same here

**Comment by dustinwloring1988** [comment]
@mredodos have you entered the api keys in the settings or are you using the .env.local?
@rezasmind need more info as well

**Comment by roodfps** [comment]
same problem here

**Comment by maskay123k** [comment]
same problem

**Comment by mredodos** [comment]
> @mredodos have you entered the api keys in the settings or are you using the .env.local? @rezasmind need more info as well

im using env.local

**Comment by dustinwloring1988** [comment]
@mredodos  try to enter them in the settings and let me know if that helps.

**Comment by davideuler** [comment]
The same problem, settings in .env.local

**Comment by automatefly** [comment]
[ERROR]
23/12/2024, 12:06:17
API connection failed
{
  "endpoint": "/api/chat",
  "retryCount": 3,
  "lastAttempt": "2024-12-23T15:06:17.946Z",
  "error": {
    "message": "Connection timeout",
    "stack": "Error: Connection timeout\n    at https://criando.wwon.com.br/app/components/settings/event-logs/EventLogsTab.tsx:63:48\n    at commitHookEffectListMount (https://criando.wwon.com.br/node_modules/.vite/deps/chunk-RMBP4JJR.js?v=6a572f6d:23793:34)\n    at commitPassiveMountOnFiber (https://criando.wwon.com.br/node_modules/.vite/deps/chunk-RMBP4JJR.js?v=6a572f6d:25034:19)\n    at commitPassiveMountEffects_complete (https://criando.wwon.com.br/node_modules/.vite/deps/chunk-RMBP4JJR.js?v=6a572f6d:25007:17)\n    at commitPassiveMountEffects_begin (https://criando.wwon.com.br/node_modules/.vite/deps/chunk-RMBP4JJR.js?v=6a572f6d:24997:15)\n    at commitPassiveMountEffects (https://criando.wwon.com.br/node_modules/.vite/deps/chunk-RMBP4JJR.js?v=6a572f6d:24987:11)\n    at flushPassiveEffectsImpl (https://criando.wwon.com.br/node_modules/.vite/deps/chunk-RMBP4JJR.js?v=6a572f6d:26368:11)\n    at flushPassiveEffects (https://criando.wwon.com.br/node_modules/.vite/deps/chunk-RMBP4JJR.js?v=6a572f6d:26325:22)\n    at commitRootImpl (https://criando.wwon.com.br/node_modules/.vite/deps/chunk-RMBP4JJR.js?v=6a572f6d:26294:13)\n    at commitRoot (https://criando.wwon.com.br/node_modules/.vite/deps/chunk-RMBP4JJR.js?v=6a572f6d:26155:13)"
  }
}


This error only happens when I import an application to continue editing, if I start a new application from scratch this problem does not occur.

![image](https://github.com/user-attachments/assets/22bf4dc2-1d77-4080-be78-63e4bfbe4bd4)

**Comment by josetiagobispo** [comment]
same problem here when cloning an application, if I start from scratch I don't get this error[ERROR]
23/12/2024, 13:46:33
API connection failed
{
  "endpoint": "/api/chat",
  "retryCount": 3,
  "lastAttempt": "2024-12-23T16:46:33.893Z",
  "error": {
    "message": "Connection timeout",
    "stack": "Error: Connection timeout\n    at http://localhost:5173/app/components/settings/event-logs/EventLogsTab.tsx:63:48\n    at commitHookEffectListMount (http://localhost:5173/node_modules/.vite/deps/chunk-RMBP4JJR.js?v=c7b73311:23793:34)\n    at commitPassiveMountOnFiber (http://localhost:5173/node_modules/.vite/deps/chunk-RMBP4JJR.js?v=c7b73311:25034:19)\n    at commitPassiveMountEffects_complete (http://localhost:5173/node_modules/.vite/deps/chunk-RMBP4JJR.js?v=c7b73311:25007:17)\n    at commitPassiveMountEffects_begin (http://localhost:5173/node_modules/.vite/deps/chunk-RMBP4JJR.js?v=c7b73311:24997:15)\n    at commitPassiveMountEffects (http://localhost:5173/node_modules/.vite/deps/chunk-RMBP4JJR.js?v=c7b73311:24987:11)\n    at flushPassiveEffectsImpl (http://localhost:5173/node_modules/.vite/deps/chunk-RMBP4JJR.js?v=c7b73311:26368:11)\n    at flushPassiveEffects (http://localhost:5173/node_modules/.vite/deps/chunk-RMBP4JJR.js?v=c7b73311:26325:22)\n    at commitRootImpl (http://localhost:5173/node_modules/.vite/deps/chunk-RMBP4JJR.js?v=c7b73311:26294:13)\n    at commitRoot (http://localhost:5173/node_modules/.vite/deps/chunk-RMBP4JJR.js?v=c7b73311:26155:13)"
  }
}

**Comment by LouiseAbela** [comment]
Did anyone manage to solve this please?

**Comment by josetiagobispo** [comment]
from the tests I did, it seems to have to do with the size of the repository, clone a small repository and do the test

**Comment by LouiseAbela** [comment]
Thanks for your answer. 

I don't even have a repo, just starting from scratch - managed to get Ollama running - it was quite strange that I had to add the url in .env also in the settings and then stop everything and start everything and start a new chat. Not sure what the problem was. Still have issues with Sonnet.

**Comment by majado2** [comment]
I have the same problem; has anyone found a solution?

**Comment by RaphPi** [comment]
Hi!
Same error here. On a new project initialized by a prompt, the AI works well, but in a project with an import folder, I get no response and a connection timeout. I think it depends on the size of the folder.

Would there be a workaround to use while waiting for a fix?

**Comment by leex279** [comment]
This is most likely a problem with the API key you using or the provider itself. For Deepseek e.g. you have to pay credits to make the API work (its not free!).
For OpenAI you also need to pay at least 5 Euro I guess to get to Tier1 and usable API.

The main branch has extended logging for the terminal (new features). Check this out, try your prompt again and check the terminal for errors.

**Comment by xKevIsDev** [comment]
This doesn't seem to be a issue in our latest version, if the issue persists try generating a new API key and try again. Else feel free to open a new issue.
