### ISSUE TITLE
There was an error processing your request: An error occurred.

### ISSUE THREAD

**Issue by Getobz** [stackblitz-labs/bolt.diy#843]
### Describe the bug

Hi there,
I have place my API key from OpenAI in my .env and on the local website but same error everytime so i cant use this chat

### Link to the Bolt URL that caused the error

http://localhost:5173/

### Steps to reproduce

1. Starting project in cmd with `pnpm run dev `
2. Go in http://localhost:5173/
3. Select OpenAI with GPT-4o
4. Writting prompt
5. Error occurred

### Expected behavior

Let it work

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/350d45de-ad73-4e52-89f0-4b8601d9658a)

### Platform

- OS: Windows
- Browser: Chrome Canary
- Version: Version 133.0.6907.0 (Build officiel) canary (64 bits)

### Provider Used

OpenAI

### Model Used

GPT-4o

**Comment by belhassinek** [comment]
Hi, same error

**Comment by actabi** [comment]
same too :-)

**Comment by roodfps** [comment]
same

**Comment by Knightcb** [comment]
same for me too

**Comment by stepolive** [comment]
Same issue

**Comment by yannicktt16** [comment]
same

**Comment by rodoll** [comment]
same too...

**Comment by justinnova0915** [comment]
same here...

**Comment by Soumyaranjan-17** [comment]
**SET in .env**
```
OLLAMA_API_BASE_URL=http://127.0.0.1:11434
```

don't set 

> OLLAMA_API_BASE_URL=http://localhost:11434
it is wrong due to some IPV6 problem 

and in UI that input field should be clear otherwise it will override the .env

![image](https://github.com/user-attachments/assets/32d00a23-786d-4a49-95e4-ebf3254f1a66)

**Comment by investdfs** [comment]
same too...

**Comment by ziedwlidha** [comment]
The issue is ongoing ?

**Comment by Soumyaranjan-17** [comment]
Hello bro, 
Hav you set the correct API key in .env file in root folder 

If yes give some screenshots of errors from terminal

**Comment by Getobz** [comment]
> Hello bro, Hav you set the correct API key in .env file in root folder
> 
> If yes give some screenshots of errors from terminal

Hello bro,
Yes i have set the correct API key in .env file in root folder

I give you a screenshot from terminal
![image](https://github.com/user-attachments/assets/32baa95a-0c1b-4203-8da2-5267ebf43c49)

**Comment by smartapp-ep** [comment]
has anyone found a solution?

**Comment by Soumyaranjan-17** [comment]
If you are running ollama locally, You must have to set the OLLAMA BASE URL = http://127.0.0.1:11434 instead of localhost:11434

**Comment by belhassinek** [comment]
A solution please

**Comment by Soumyaranjan-17** [comment]
> A solution please

Can you share your setup 
What model you are using 
And anything you facing

**Comment by fastuptime** [comment]
> > A solution please
> 
> Can you share your setup What model you are using And anything you facing

There was an error processing your request: An error occurred.
![image](https://github.com/user-attachments/assets/8a792f68-6f8c-4f57-8f96-d45f1bc451d2)
![image](https://github.com/user-attachments/assets/80d0cb25-1715-4b80-b631-de0e08836179)
![image](https://github.com/user-attachments/assets/7b367cab-7c89-4957-8a73-ba4b9652fa21)

**Comment by Soumyaranjan-17** [comment]
Okey found it

Instead of using http://localhost:11434
Use **http://127.0.0.1:11434**  wherever you use it 

Because IPV6 conversation will convert localhost to ::1:11434

**Comment by fastuptime** [comment]
> Okey found it
> 
> Instead of using http://localhost:11434 Use **http://127.0.0.1:11434** wherever you use it
> 
> Because IPV6 conversation will convert localhost to ::1:11434

It didn't work

**Comment by Soumyaranjan-17** [comment]
Change .env.example -> .env
In .env set the base url of ollama as http://127.0.0.1:11434

> Don't use extra space after it 
> Check if the ollama is running or not 

And if you have set the OLLAMA_BASE_URL in the **BOLT UI** > Setting > Providers 
Then change it to http://127.0.0.1:11434 also or keep it blank

**Comment by fastuptime** [comment]
> Change .env.example -> .env In .env set the base url of ollama as http://127.0.0.1:11434
> 
> > Don't use extra space after it
> > Check if the ollama is running or not
> 
> And if you have set the OLLAMA_BASE_URL in the **BOLT UI** > Setting > Providers Then change it to http://127.0.0.1:11434 also or keep it blank

The settings are already that way now, but the problem still persists.

Ollama logs;

Dec 24 14:30:36 Can ollama[259]: [GIN] 2024/12/24 - 14:30:36 | 200 |    1.289096ms |       127.0.0.1 | GET      "/api/version"
Dec 24 14:33:52 Can ollama[259]: [GIN] 2024/12/24 - 14:33:52 | 200 |    9.732224ms |       127.0.0.1 | GET      "/api/tags"
Dec 24 14:34:02 Can ollama[259]: [GIN] 2024/12/24 - 14:34:02 | 200 |      423.51µs |       127.0.0.1 | GET      "/api/tags"
Dec 24 14:45:24 Can ollama[259]: [GIN] 2024/12/24 - 14:45:24 | 200 |      54.596µs |       127.0.0.1 | GET      "/"
Dec 24 14:45:25 Can ollama[259]: [GIN] 2024/12/24 - 14:45:25 | 404 |       6.442µs |       127.0.0.1 | GET      "/favicon.ico"
Dec 24 14:45:46 Can ollama[259]: [GIN] 2024/12/24 - 14:45:46 | 200 |   11.318114ms |       127.0.0.1 | GET      "/api/tags"
Dec 24 14:46:05 Can ollama[259]: [GIN] 2024/12/24 - 14:46:05 | 200 |     514.286µs |       127.0.0.1 | GET      "/api/tags"
Dec 24 14:46:09 Can ollama[259]: [GIN] 2024/12/24 - 14:46:09 | 200 |     608.689µs |       127.0.0.1 | GET      "/api/tags"
Dec 24 14:54:03 Can ollama[259]: [GIN] 2024/12/24 - 14:54:03 | 200 |       71.99µs |       127.0.0.1 | GET      "/"
Dec 24 14:55:14 Can ollama[259]: [GIN] 2024/12/24 - 14:55:14 | 200 |      28.265µs |       127.0.0.1 | GET      "/"
Dec 24 14:55:20 Can ollama[259]: [GIN] 2024/12/24 - 14:55:20 | 200 |     665.629µs |       127.0.0.1 | GET      "/api/tags"
Dec 24 14:55:23 Can ollama[259]: [GIN] 2024/12/24 - 14:55:23 | 200 |     580.287µs |       127.0.0.1 | GET      "/api/tags"
Dec 24 14:55:34 Can ollama[259]: [GIN] 2024/12/24 - 14:55:34 | 200 |     442.908µs |       127.0.0.1 | GET      "/api/tags"
Dec 24 14:55:34 Can ollama[259]: [GIN] 2024/12/24 - 14:55:34 | 404 |   10.754563ms |       127.0.0.1 | POST     "/api/chat"
Dec 24 14:55:52 Can ollama[259]: [GIN] 2024/12/24 - 14:55:52 | 200 |     471.022µs |       127.0.0.1 | GET      "/api/tags"
Dec 24 14:55:52 Can ollama[259]: [GIN] 2024/12/24 - 14:55:52 | 404 |      790.32µs |       127.0.0.1 | POST     "/api/chat"

**Comment by Soumyaranjan-17** [comment]
You will have to go to the providers from the settings tab and scroll down to ollama and paste ollama base url as - http://127.0.0.1:11434 (default port used to interact with ollama). Refresh and it shows up now.

**Comment by fastuptime** [comment]
> You will have to go to the providers from the settings tab and scroll down to ollama and paste ollama base url as - http://127.0.0.1:11434 (default port used to interact with ollama). Refresh and it shows up now.

Hello again, ollama working on the default port and my settings and other configurations are as you said.

**Comment by Soumyaranjan-17** [comment]
> > Hello bro, Hav you set the correct API key in .env file in root folder
> > If yes give some screenshots of errors from terminal
> 
> Hello bro, Yes i have set the correct API key in .env file in root folder
> 
> I give you a screenshot from terminal ![image](https://private-user-images.githubusercontent.com/69972159/398123729-32baa95a-0c1b-4203-8da2-5267ebf43c49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNDUxMjMsIm5iZiI6MTczNTA0NDgyMywicGF0aCI6Ii82OTk3MjE1OS8zOTgxMjM3MjktMzJiYWE5NWEtMGMxYi00MjAzLThkYTItNTI2N2ViZjQzYzQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDEyNTM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYmQyYmJkODkyNWIzNWEwYTNiMDkxYTZhYzliMDkzZDFlY2FhMjlhNDJlM2M2MjU1YWQwMjQ2ZDkwOTMzNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x7oznpqT3PFq989A8V9jzdNHOdpBxhhKPNs62GUsZWw)


Is this the problem you are facing...

This is how I fixed that issue by myself 
If it is not working then try to brainstorm

**Comment by justinnova0915** [comment]
Hello,

I'm using ollama and the models just don't show up. The settings page is blank, API key is blank, and I set the .env file to http://127.0.0.1:11434. ths is what the console show me:
![image](https://github.com/user-attachments/assets/daa96e3b-ac69-4b58-86be-41b8d4d357a7)

![image](https://github.com/user-attachments/assets/e007f763-f562-4c37-b9d4-c6187b4b3683)

Please Help :(

**Comment by justinnova0915** [comment]
> Hello,
> 
> I'm using ollama and the models just don't show up. The settings page is blank, API key is blank, and I set the .env file to http://127.0.0.1:11434. ths is what the console show me: ![image](https://private-user-images.githubusercontent.com/120691190/398433563-daa96e3b-ac69-4b58-86be-41b8d4d357a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNTIyMjgsIm5iZiI6MTczNTA1MTkyOCwicGF0aCI6Ii8xMjA2OTExOTAvMzk4NDMzNTYzLWRhYTk2ZTNiLWFjNjktNGI1OC04NmJlLTQxYjhkNGQzNTdhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQxNDUyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00M2I1MWJlMTFkZmYwNjFiNGNhOGU2YTRjNjYyOTQ4ZmZlYzYxMzBjM2JkNjRmZjY3MjAxODNhNzIyMzc4MDU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wYbQUhup93Z9MGzyuC0vpwPkf6ab-TpKVa3N3UqBUn4)
> 
> ![image](https://private-user-images.githubusercontent.com/120691190/398433406-e007f763-f562-4c37-b9d4-c6187b4b3683.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNTIyMjgsIm5iZiI6MTczNTA1MTkyOCwicGF0aCI6Ii8xMjA2OTExOTAvMzk4NDMzNDA2LWUwMDdmNzYzLWY1NjItNGMzNy1iOWQ0LWM2MTg3YjRiMzY4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQxNDUyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMmQzY2U3MDU2ZjRiYzJmZjk5ZDBiYzdmM2YzNzM5OGIyYjk1Yzk0MzRkNWM4MzA2Njc2NjcwYzg0ZDQwMzFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wVbTYYxrrrT8dv4ThdiADAfRgPYxwfERBX8PRTJ3fDs)
> 
> Please Help :(

Update: I reinstalled Ollama so now the models appear, but  when I try messaging my models, it still shows the error message both in the console and on the webpage.

**Comment by Soumyaranjan-17** [comment]
Let me clarify some important steps for local ollama model
1. Download Ollama
2. Download your desired model according to your **_machine capability._**
3. Open the project file 
4. Rename .env.example to .env
5. Inside .env set the OLLAMA_API_BASE_URL=http://127.0.0.1:11434
> ### DONT USE http://localhost:11434 due to IPV6 issues
6. If you have previously set the OLLAMA_API_BASE_URL inside the BOLT website's setting page > provider, then clear that (if you don't understand this line, let me know)
7. Restart the server
8. Connect to a good network (as the web container is being fetched from stackblitz server 
9. Make sure to start the ollama server (you can check it here [OLLAMA API BASE URL](http://127.0.0.1:11434) )

**Comment by Soumyaranjan-17** [comment]
> Hello,
> 
> I'm using ollama and the models just don't show up. The settings page is blank, API key is blank, and I set the .env file to http://127.0.0.1:11434. ths is what the console show me: ![image](https://private-user-images.githubusercontent.com/120691190/398433563-daa96e3b-ac69-4b58-86be-41b8d4d357a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNTQ0MzcsIm5iZiI6MTczNTA1NDEzNywicGF0aCI6Ii8xMjA2OTExOTAvMzk4NDMzNTYzLWRhYTk2ZTNiLWFjNjktNGI1OC04NmJlLTQxYjhkNGQzNTdhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQxNTI4NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWMzMzFiZTU0MjgyYWExOWQ2NjRkNDQ5NjI3NmUzMWQ3N2E3NDE0MjMyNmRiMWY0YjIzMzIzY2ZlOWVmMzZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QX27aNuBKtxqzIiMSJ4FVsKAFT4Sms0uSE265Bgfqn4)
> 
> ![image](https://private-user-images.githubusercontent.com/120691190/398433406-e007f763-f562-4c37-b9d4-c6187b4b3683.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNTQ0MzcsIm5iZiI6MTczNTA1NDEzNywicGF0aCI6Ii8xMjA2OTExOTAvMzk4NDMzNDA2LWUwMDdmNzYzLWY1NjItNGMzNy1iOWQ0LWM2MTg3YjRiMzY4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQxNTI4NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTdlOWQ0NGM1MzE5NTc2MmVkMWQyNzM4MjFlNmY4YjM1ODk3Mjc2YjJkMmFlMzNlNDc4ZGE0Mzc3NmIxMDI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Kz5R6J4hWok58SfYmRiGNf8HK73krjbZUmo_kyKFNaA)
> 
> Please Help :(

You have some messages inside your console, but it is hidden as you haven't scroll down 🙄

**Comment by justinnova0915** [comment]
> > Hello,
> 
> > 
> 
> > I'm using ollama and the models just don't show up. The settings page is blank, API key is blank, and I set the .env file to http://127.0.0.1:11434. ths is what the console show me: ![image](https://private-user-images.githubusercontent.com/120691190/398433563-daa96e3b-ac69-4b58-86be-41b8d4d357a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNTQ0MzcsIm5iZiI6MTczNTA1NDEzNywicGF0aCI6Ii8xMjA2OTExOTAvMzk4NDMzNTYzLWRhYTk2ZTNiLWFjNjktNGI1OC04NmJlLTQxYjhkNGQzNTdhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQxNTI4NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWMzMzFiZTU0MjgyYWExOWQ2NjRkNDQ5NjI3NmUzMWQ3N2E3NDE0MjMyNmRiMWY0YjIzMzIzY2ZlOWVmMzZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QX27aNuBKtxqzIiMSJ4FVsKAFT4Sms0uSE265Bgfqn4)
> 
> > 
> 
> > ![image](https://private-user-images.githubusercontent.com/120691190/398433406-e007f763-f562-4c37-b9d4-c6187b4b3683.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNTQ0MzcsIm5iZiI6MTczNTA1NDEzNywicGF0aCI6Ii8xMjA2OTExOTAvMzk4NDMzNDA2LWUwMDdmNzYzLWY1NjItNGMzNy1iOWQ0LWM2MTg3YjRiMzY4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQxNTI4NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTdlOWQ0NGM1MzE5NTc2MmVkMWQyNzM4MjFlNmY4YjM1ODk3Mjc2YjJkMmFlMzNlNDc4ZGE0Mzc3NmIxMDI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Kz5R6J4hWok58SfYmRiGNf8HK73krjbZUmo_kyKFNaA)
> 
> > 
> 
> > Please Help :(
> 
> 
> 
> You have some messages inside your console, but it is hidden as you haven't scroll down 🙄

The rest is just more fetch failed errors

**Comment by justinnova0915** [comment]
> Let me clarify some important steps for local ollama model
> 
> 1. Download Ollama
> 
> 2. Download your desired model according to your **_machine capability._**
> 
> 3. Open the project file 
> 
> 4. Rename .env.example to .env
> 
> 5. Inside .env set the OLLAMA_API_BASE_URL=http://127.0.0.1:11434
> 
> > ### DONT USE http://localhost:11434 due to IPV6 issues
> 
> 6. If you have previously set the OLLAMA_API_BASE_URL inside the BOLT website's setting page > provider, then clear that (if you don't understand this line, let me know)
> 
> 7. Restart the server
> 
> 8. Connect to a good network (as the web container is being fetched from stackblitz server 
> 
> 9. Make sure to start the ollama server (you can check it here [OLLAMA API BASE URL](http://127.0.0.1:11434) )

I can confirm that I did all that.

**Comment by investdfs** [comment]
> Okey encontrou-o
> 
> Em vez de usar http://localhost:11434Usar **http://127.0.0.1:11434** onde quer que o uses
> 
> Porque a conversa IPV6 converterá localhost para::1:11434

**Mayor, you solved my problem, excellent tip. You are the man! Thank you.**

**Comment by investdfs** [comment]
After many tests and trying all the tips I found on the internet, only one solution worked.

Although it seems like a local problem, or in the platform, it is actually an API problem, or rather, it seems to me that somehow the APIs are not recognizing or validating the requests from the local Bolt, and I can't imagine why this is happening.

The only solution that worked for me was to disable all providers and base urls, except Mistral. I created an API to use with Mistral Large Las, and bingo! Everything worked perfectly.

![image](https://github.com/user-attachments/assets/987e4948-8e2f-4e5a-9057-cfdfd225ccff)

**I hope it works for you!**

**Comment by Soumyaranjan-17** [comment]
So what is someone what's to use local llm such as ollama

**Comment by yannicktt16** [comment]
As in the original request I tried using OpenAI's GPT-4o Model. However, even though I configured the API key as explained by OpenAI and in the git-repo, i get the error "There was an error processing your request: An error occurred."

In the Terminal i get the error "WARN Constants Failed to get Ollama models:  fetch failed".

Why is that? As far as I understood we do not need to have Ollama running to use the OpenAI model?
I also disabled all providers except of OpenAI.

Maybe I do not understand that correctly but I guess this is an issue for many...

Setup:
Macbook Pro
MacOS Sequoia 15.3
Google Chrome
OpenAI GPT-4o Model

**Comment by raifflucena** [comment]
Same here. I tried with 4o and Gemini 1.5 Flash running on docker.

**Comment by barhom** [comment]
Same here, not trying to run ollama but gettnig ollama errors

**Comment by iamthemediagit** [comment]
Same error on mac.
ECONNREFUSED 

Checked firewall rules ...


Log message :
Failed to get Ollama models: TypeError: fetch failed
app-dev-1  |     at node:internal/deps/undici/undici:13185:13
app-dev-1  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
app-dev-1  |     at OllamaProvider.getDynamicModels (/app/app/lib/modules/llm/providers/ollama.ts:41:24)
app-dev-1  |     at async Promise.all (index 0)
app-dev-1  |     at LLMManager.updateModelList (/app/app/lib/modules/llm/manager.ts:71:27)
app-dev-1  |     at Module.getModelList (/app/app/utils/constants.ts:43:10)
app-dev-1  |     at Module.streamText (/app/app/lib/.server/llm/stream-text.ts:99:22)
app-dev-1  |     at chatAction (/app/app/routes/api.chat.ts:101:20)
app-dev-1  |     at Object.callRouteAction (/app/node_modules/.pnpm/@remix-run+server-runtime@2.15.0_typescript@5.7.2/node_modules/@remix-run/server-runtime/dist/data.js:36:16)
app-dev-1  |     at /app/node_modules/.pnpm/@remix-run+router@1.21.0/node_modules/@remix-run/router/router.ts:4899:19
app-dev-1  |     at callLoaderOrAction (/app/node_modules/.pnpm/@remix-run+router@1.21.0/node_modules/@remix-run/router/router.ts:4963:16)
app-dev-1  |     at async Promise.all (index 0)
app-dev-1  |     at defaultDataStrategy (/app/node_modules/.pnpm/@remix-run+router@1.21.0/node_modules/@remix-run/router/router.ts:4772:17)
app-dev-1  |     at callDataStrategyImpl (/app/node_modules/.pnpm/@remix-run+router@1.21.0/node_modules/@remix-run/router/router.ts:4835:17)
app-dev-1  |     at callDataStrategy (/app/node_modules/.pnpm/@remix-run+router@1.21.0/node_modules/@remix-run/router/router.ts:3992:19)
app-dev-1  |     at submit (/app/node_modules/.pnpm/@remix-run+router@1.21.0/node_modules/@remix-run/router/router.ts:3755:21)
app-dev-1  |     at queryImpl (/app/node_modules/.pnpm/@remix-run+router@1.21.0/node_modules/@remix-run/router/router.ts:3684:22)
app-dev-1  |     at Object.queryRoute (/app/node_modules/.pnpm/@remix-run+router@1.21.0/node_modules/@remix-run/router/router.ts:3629:18)
app-dev-1  |     at handleResourceRequest (/app/node_modules/.pnpm/@remix-run+server-runtime@2.15.0_typescript@5.7.2/node_modules/@remix-run/server-runtime/dist/server.js:402:20)
app-dev-1  |     at requestHandler (/app/node_modules/.pnpm/@remix-run+server-runtime@2.15.0_typescript@5.7.2/node_modules/@remix-run/server-runtime/dist/server.js:156:18)
app-dev-1  |     at /app/node_modules/.pnpm/@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_3djlhh3t6jbfog2cydlrvgreoy/node_modules/@remix-run/dev/dist/vite/cloudflare-proxy-plugin.js:70:25 {
app-dev-1  |   [cause]: Error: connect ECONNREFUSED 127.0.0.1:11434
app-dev-1  |       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
app-dev-1  |       at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
app-dev-1  |     errno: -111,
app-dev-1  |     code: 'ECONNREFUSED',
app-dev-1  |     syscall: 'connect',
app-dev-1  |     address: '127.0.0.1',
app-dev-1  |     port: 11434
app-dev-1  |   }
app-dev-1  | }

**Comment by rexsama** [comment]
Not sure what's going on, after update the latest version today, I have this issue and I cannot started.
![image](https://github.com/user-attachments/assets/95757a0d-9cb0-4fcb-97b1-2cfabb916ba0)

Also, if I move "mouse" to the side menu, I will get another issue. The fact is, I cannot save or load chat history.
![image](https://github.com/user-attachments/assets/a24dadb9-71ab-418b-a16a-4650b7ae4f79)

I set .env file.

DEFAULT_NUM_CTX = 6144 as I am using a 3090 24G VRAM, I think I can set 32768.
OLLAMA_API_BASE_URL= http://127.0.0.1:11434

Any thought? Am I the only one having the both errors?

**Comment by jyotisah00** [comment]
my browser was fixed after changing .env.example to .env
but now bolt is getting stuck here :
2025-01-03 19:47:12 app-dev-1  |  INFO   LLMManager  Getting dynamic models for Ollama
2025-01-03 19:47:12 app-dev-1  |  INFO   LLMManager  Got 4 dynamic models for Ollama
2025-01-03 19:47:12 app-dev-1  |  INFO   stream-text  Sending llm call to Ollama with model codegemma:latest
2025-01-03 19:52:45 app-dev-1  |  INFO   LLMManager  Found 4 cached models for Ollama
2025-01-03 19:52:45 app-dev-1  |  INFO   stream-text  Sending llm call to Ollama with model codegemma:latest
2025-01-03 19:53:31 app-dev-1  |  INFO   LLMManager  Getting dynamic models for Ollama
2025-01-03 19:53:31 app-dev-1  |  INFO   LLMManager  Got 4 dynamic models for Ollama
2025-01-03 19:53:31 app-dev-1  |  INFO   stream-text  Sending llm call to Ollama with model codegemma:latest
2025-01-03 19:54:11 app-dev-1  |  INFO   LLMManager  Found 4 cached models for Ollama
2025-01-03 19:54:11 app-dev-1  |  INFO   stream-text  Sending llm call to Ollama with model llama2:latest

**Comment by mikheyrojo** [comment]
Guys, getting any error from LLM -> you will get this behaviour, e.g. context length is too big (e.g. my project was too big and tried to send all node modules, source maps, yarn.loc etc) and some models are not build for it.

**Comment by HCOSCARELLI** [comment]
![image](https://github.com/user-attachments/assets/247785f0-2a3c-4728-a746-c08f733613b2)

i need help

**Comment by abhishek207** [comment]
Facing the same issue with almost every model, it works on initial request then i get the same error message, if someone find the fix please let me know, i am thinking to try it without the docker once to see if that works

**Comment by iamthemediagit** [comment]
Guys, Here the solution.
> Easy way for mac, windows and linux, 
give a try to pinokio.computer. 
2 click installation with conda env

> Manually
Was unable to run docker version but with pnpm finally worked
you have to create manually the .env 
cp .env.example .env 
Then edit .env with ollama url for example
 
**If you already installed with pnpm, clean everything:**
# Remove node modules and lock files
rm -rf node_modules pnpm-lock.yaml

# Clear pnpm cache
pnpm store prune
  
Have all a good year

**Comment by jyotisah00** [comment]
> After many tests and trying all the tips I found on the internet, only one solution worked.
> 
> Although it seems like a local problem, or in the platform, it is actually an API problem, or rather, it seems to me that somehow the APIs are not recognizing or validating the requests from the local Bolt, and I can't imagine why this is happening.
> 
> The only solution that worked for me was to disable all providers and base urls, except Mistral. I created an API to use with Mistral Large Las, and bingo! Everything worked perfectly.
> 
> ![image](https://private-user-images.githubusercontent.com/140403943/398566683-987e4948-8e2f-4e5a-9057-cfdfd225ccff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNTM1MTQsIm5iZiI6MTczNjE1MzIxNCwicGF0aCI6Ii8xNDA0MDM5NDMvMzk4NTY2NjgzLTk4N2U0OTQ4LThlMmYtNGU1YS05MDU3LWNmZGZkMjI1Y2NmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNlQwODQ2NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYWZiMTVmMTY1N2I4MzczMWRiOTM3MTM0MzY3NzI0OWU3YmZmZjJkZjU1ODJiYWI1MmNkZWQ4NjkyMDViNTZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bpGamND_d4UxJWGBWP5aaCttJBLQBQtAlfdv1zWUrhE)
> 
> **I hope it works for you!**

thanks this worked after weeks of troubleshooting. i was running ollama on a different server

**Comment by monnyahmeti** [comment]
![Capture2](https://github.com/user-attachments/assets/ae402138-a195-465f-8d7b-9570e3efc656)

Can someone help

**Comment by leex279** [comment]
This is most likely a problem with the API key you using or the provider itself. For Deepseek e.g. you have to pay credits to make the API work (its **not** free!).
For OpenAI you also need to pay at least 5 Euro I guess to get to Tier1 and usable API.

The **main** branch has extended logging for the terminal (new features). Check this out, try your prompt again and check the terminal for errors.

**Comment by xKevIsDev** [comment]
This is no longer an issue in our latest main branch. Chat context is also much smaller.

Ensure when using various models that a valid API Key is set from that provider.
