### ISSUE TITLE
Cannot read properties of undefined (reading 'toolCalls')

### ISSUE THREAD

**Issue by 500Kilogram** [stackblitz-labs/bolt.diy#860]
### Describe the bug

I have installed qwen2.5-coder. I launched bolt in pinokio. And I'm making a mistake.

### Link to the Bolt URL that caused the error

/

### Steps to reproduce

bolt launch in pinokio
The choice of ollama - qwen2.5-coder:32b
promt

### Expected behavior

start

### Screen Recording / Screenshot

![Снимок](https://github.com/user-attachments/assets/33d56383-1f6b-4ca5-b6fe-7d7a4801264b)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Provider Used

ollama

### Model Used

qwen2.5-coder:32b

### Additional context

![image](https://github.com/user-attachments/assets/084a6e39-9c27-4a2a-b322-5692f270a2df)
this happens when the promt improves.

**Comment by nzgl-g** [comment]
> ### Describe the bug
> I have installed qwen2.5-coder. I launched bolt in pinokio. And I'm making a mistake.
> 
> ### Link to the Bolt URL that caused the error
> /
> 
> ### Steps to reproduce
> bolt launch in pinokio The choice of ollama - qwen2.5-coder:32b promt
> 
> ### Expected behavior
> start
> 
> ### Screen Recording / Screenshot
> ![Снимок](https://private-user-images.githubusercontent.com/168112138/397919998-33d56383-1f6b-4ca5-b6fe-7d7a4801264b.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODQ4MDEsIm5iZiI6MTczNDc4NDUwMSwicGF0aCI6Ii8xNjgxMTIxMzgvMzk3OTE5OTk4LTMzZDU2MzgzLTFmNmItNGNhNS1iNmZlLTdkN2E0ODAxMjY0Yi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQxMjM1MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YzYzMjVmMTU5YjZhMTE5ZThhN2Q1OWQ0OTViODJlNDdiNjE0ODcyMTFlZjExN2Q2NGE3NzI0NjBhY2E2NDVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HBvBi_7cQz2e6vyird8cC56FB7KD5SSZ2NnM6jng_JU)
> 
> ### Platform
> * OS: [e.g. macOS, Windows, Linux]
> * Browser: [e.g. Chrome, Safari, Firefox]
> * Version: [e.g. 91.1]
> 
> ### Provider Used
> ollama
> 
> ### Model Used
> qwen2.5-coder:32b
> 
> ### Additional context
> ![image](https://private-user-images.githubusercontent.com/168112138/397920087-084a6e39-9c27-4a2a-b322-5692f270a2df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODQ4MDEsIm5iZiI6MTczNDc4NDUwMSwicGF0aCI6Ii8xNjgxMTIxMzgvMzk3OTIwMDg3LTA4NGE2ZTM5LTljMjctNGEyYS1iMzIyLTU2OTJmMjcwYTJkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQxMjM1MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZWQ2MTc3ZDYxZmQ2MDUwOTI1NjhjNWMyODQ0NmZlNDJiYzE4ZTcxY2Y5NGUxNjFkOWE4YzA0ODdhN2NiMWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rOZRonDFgzFlzTeXrp5rBwe5VHu2uau8xcA_Y_oHRcM) this happens when the promt improves.

I have this issue too , hope they fix it

**Comment by b22-dev** [comment]
same issue here

**Comment by thecodacus** [comment]
can you try other provider?

**Comment by ZakhilAmin** [comment]
Same issue here, i have tried using Node.js on local computer

**Comment by kayed85** [comment]
Same issue here, Macbook Pro M1 Pro , macOS Sequoia 15.2
<img width="1493" alt="Screenshot 2024-12-22 at 12 02 03 AM" src="https://github.com/user-attachments/assets/6e42c19e-2258-47bb-8c87-2ffdd7ef5f93" />

**Comment by Ibaad-Ur-Rehman** [comment]
same issue with me

**Comment by b22-dev** [comment]
The same issue even if I used other providers.

I tested it using this providers:
TogetherAI
Groq
xAi

Anyway, it worked with local OLlama (Llama 3.1 (8B)).

Device:
MacBook M1 Pro.

**Comment by thecodacus** [comment]
happens in two scenario, your models were not selected correctly and its using default model instead of selected model
or you have set the api key wrong 

can you set the api keys on the UI and just switch the model dropdown to some other model and then back to the one you want to use, "model" not the "provider"

**Comment by thecodacus** [comment]
> EDIT: I tried to track **NETWORK** browser traffic to identify the issue. Anyway, The response of the request is **EMPTY**, and for the payload I can see that the api key is registered and everything looks fine but the request being responded with error.

were you able to check the selected model? thats in the messages and prefixed in the content of the user message

**Comment by beenycool** [comment]
same happens to me it just stopped working after i finally got it running. I got this in the console:TypeError: Cannot read properties of undefined (reading 'toolCalls')
    at Object.flush (file:///C:/Users/******/Documents/soody/website/bolt.diy-0.0.3/node_modules/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/core/generate-text/stream-text.ts:569:33)
    at ensureIsPromise (node:internal/webstreams/util:192:19)
    at transformStreamDefaultSinkCloseAlgorithm (node:internal/webstreams/transformstream:569:5)
    at Object.close (node:internal/webstreams/transformstream:366:14)
    at ensureIsPromise (node:internal/webstreams/util:192:19)
    at writableStreamDefaultControllerProcessClose (node:internal/webstreams/writablestream:1142:28)
    at writableStreamDefaultControllerAdvanceQueueIfNeeded (node:internal/webstreams/writablestream:1222:5)
    at writableStreamDefaultControllerClose (node:internal/webstreams/writablestream:1189:3)
    at writableStreamClose (node:internal/webstreams/writablestream:699:3)
    at writableStreamDefaultWriterClose (node:internal/webstreams/writablestream:1071:10)
    at writableStreamDefaultWriterCloseWithErrorPropagation (node:internal/webstreams/writablestream:1063:10)
    at node:internal/webstreams/readablestream:1439:15
    at complete (node:internal/webstreams/readablestream:1312:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
21:38:24 [vite] Internal server error: Cannot read properties of undefined (reading 'toolCalls')
      at Object.flush (file:///C:/Users/******/Documents/soody/website/bolt.diy-0.0.3/node_modules/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/core/generate-text/stream-text.ts:569:33)
      at ensureIsPromise (node:internal/webstreams/util:192:19)
      at transformStreamDefaultSinkCloseAlgorithm (node:internal/webstreams/transformstream:569:5)
      at Object.close (node:internal/webstreams/transformstream:366:14)
      at ensureIsPromise (node:internal/webstreams/util:192:19)
      at writableStreamDefaultControllerProcessClose (node:internal/webstreams/writablestream:1142:28)
      at writableStreamDefaultControllerAdvanceQueueIfNeeded (node:internal/webstreams/writablestream:1222:5)
      at writableStreamDefaultControllerClose (node:internal/webstreams/writablestream:1189:3)
      at writableStreamClose (node:internal/webstreams/writablestream:699:3)
      at writableStreamDefaultWriterClose (node:internal/webstreams/writablestream:1071:10)
      at writableStreamDefaultWriterCloseWithErrorPropagation (node:internal/webstreams/writablestream:1063:10)
      at node:internal/webstreams/readablestream:1439:15
      at complete (node:internal/webstreams/readablestream:1312:9)
      at processTicksAndRejections (node:internal/process/task_queues:95:5) (x4)

**Comment by vrcnx** [comment]
Same issue here, was working fine then I attempted to upload a .py file and then that error occurred. Using Claude 3.5 sonnet. 

I also have an open ai api key i tried using, 4o mini worked, but 4o didn't work.

**Comment by b22-dev** [comment]
> > EDIT: I tried to track **NETWORK** browser traffic to identify the issue. Anyway, The response of the request is **EMPTY**, and for the payload I can see that the api key is registered and everything looks fine but the request being responded with error.
> 
> were you able to check the selected model? thats in the messages and prefixed in the content of the user message

**Yes**, I can see it there.


> [Model: grok-2-1212]\n\n[Provider: xAI]\n\n

**Comment by beenycool** [comment]
any fixes?

**Comment by digason** [comment]
As a temporary fix, after you activate the venv, you can do the following to rollback the huggingface_hub package, which is the source of the issue.

```
pip uninstall -y huggingface_hub
pip install huggingface_hub==0.25.2
```

**Comment by devictang** [comment]
I have the same issue when connected with Claude AI, I have saved API key to .env.local but it's still not working. Ollama model running locally works though.

**Comment by BrianLFuller** [comment]
I'm having the same issue. I'm on. a Mac M1  running Sequoia 15.2.
Tried running in Docker and with pnpm. Tried using Chrome Canary, and Brave browser. 
Happens with local Ollama and OpenAI with key.  I've tried running from localhost:5173 and 172.0.0.1:5173. Getting same issue across the board.

**Comment by ThibaultBarral** [comment]
I have the same problem as all of you I am Sequoia 15.1.1

**Comment by thecodacus** [comment]
will look into this

**Comment by b22-dev** [comment]
> will look into this

Thank you for your efforts.

**Comment by devanubhav** [comment]
I read that it was related to docker..i ran docker as per setup instruction but didnt work either

**Comment by ThibaultBarral** [comment]
me too, I think it's linked to the M1 chip

**Comment by devanubhav** [comment]
<img width="1383" alt="Screenshot 2024-12-26 at 6 51 51 PM" src="https://github.com/user-attachments/assets/4f4eb2ab-7d59-4945-9f35-f77b57bc2fcf" />
worked with llama3(8b) but as visible in the screenshot, it didnt loan in the container

**Comment by devictang** [comment]
> me too, I think it's linked to the M1 chip

Same, I'm using M chips too, probably this is what causing the problem.

**Comment by galaridor** [comment]
I have the same issue, and i do not believe it is related to the M1 chip since i am having it on AMD 7th gen processor

**Comment by ThibaultBarral** [comment]
in any case, I can't wait to use it on my computer and for the bug to be fixed.

**Comment by galaridor** [comment]
hope it is fixed soon as well. Is it possible that we messed up with setup and did not set it up properly? I guess it is

**Comment by ThibaultBarral** [comment]
I don't think so because I've done all 3 possible installations.

**Comment by webita** [comment]
I have M4 an have the same problem (installed via Pinokio)...Anyone have founded a solution?
I have tried to downgrade huggingface-hub but don't work.

**Comment by galaridor** [comment]
Installing dependencies using pnpm instead of npm led to a different problem. Seems like the old is not showing anymore tho. 

![image_2024-12-26_174944747](https://github.com/user-attachments/assets/7968e6cf-353c-4425-bbec-fd03b9b71118)

**Comment by thecodacus** [comment]
> <img alt="Screenshot 2024-12-26 at 6 51 51 PM" width="1383" src="https://private-user-images.githubusercontent.com/10047678/398735997-4f4eb2ab-7d59-4945-9f35-f77b57bc2fcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNDU5MjEsIm5iZiI6MTczNTI0NTYyMSwicGF0aCI6Ii8xMDA0NzY3OC8zOTg3MzU5OTctNGY0ZWIyYWItN2Q1OS00OTQ1LTlmMzUtZjc3YjU3YmMyZmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDIwNDAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzZTgxYTdmNTk2NDc5MWQ2Y2E0OGY5NjFlMWQ1NTEzNzZhMWQyMTBjODNhMWQ0NjM5MDhmOTYzYmFlOTBlYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MYVrLHPf5Otu0ysrqVKjkmZO5r8oVdZcvBUAZ4UeEY8"> worked with llama3(8b) but as visible in the screenshot, it didnt loan in the container

this is llm not following instructions. to open a container the llm has to write the code is a special tags this its not doing it.
i often see smaller llm not able to follow system prompt correctly. try with other models like Togather AI, its free

**Comment by ReEnvisionAi** [comment]
Looking at the error I believe its related to the vecel api being used for model switching. But its just a theory.

**Comment by twestphq** [comment]
I'm having this issue as well. I've spent days trying to fix it. 
- Different browsers
- Different versions of bolt
- Different LLMs
- Docker, normal install
- Different projects
- Troubleshooting different projects, uninstalling, reinstalling dependencies, etc, etc
The list goes on. I start from scratch, get my project set up, I get X part of the way through, then error, troubleshoot, unfixable, start again. 

Cannot read properties of undefined (reading 'toolCalls')
    at Object.flush (file:///C:/Users/twest/bolt.diy/node_modules/ai/core/generate-text/stream-text.ts:569:33)
    at ensureIsPromise (node:internal/webstreams/util:192:19)
    at transformStreamDefaultSinkCloseAlgorithm (node:internal/webstreams/transformstream:569:5)
    at Object.close (node:internal/webstreams/transformstream:366:14)
    at ensureIsPromise (node:internal/webstreams/util:192:19)
    at writableStreamDefaultControllerProcessClose (node:internal/webstreams/writablestream:1142:28)
    at writableStreamDefaultControllerAdvanceQueueIfNeeded (node:internal/webstreams/writablestream:1222:5)
    at writableStreamDefaultControllerClose (node:internal/webstreams/writablestream:1189:3)
    at writableStreamClose (node:internal/webstreams/writablestream:699:3)
    at writableStreamDefaultWriterClose (node:internal/webstreams/writablestream:1071:10)
    at writableStreamDefaultWriterCloseWithErrorPropagation (node:internal/webstreams/writablestream:1063:10)
    at node:internal/webstreams/readablestream:1439:15
    at complete (node:internal/webstreams/readablestream:1312:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5

**Comment by galaridor** [comment]
1. rename the env file to just ".env" and set the API key or base URL there. If you are using local model don't use localhost, use 127.0.0.1 instead. 
2. Change the "dev" script in the package.json file to "remix vite:dev --host 0.0.0.0 --port {your port} --open"

This actually did the job for me and now everything works locally using ollama

**Comment by basil2style** [comment]
@galaridor I just tried this but not working for me :(

**Comment by BrianLFuller** [comment]
@galaridor may be on to something. 
Instead of renaming my .env.local, I made a copy of it and named it .env.  I now have both in the root of my project.
After grabbing the latest main branch, and changing my dev script to this:
 "dev": "node pre-start.cjs  && remix vite:dev --host 0.0.0.0 --port 5173 --open",
 I did a pnpm install, and pnpm run dev. I was able to get a response using the Ollama 3.2 model. The Ollama 3.3 I think is timing out, and my OpenAI attempts still don't work.
 Running in docker still gives the Cannot read properties of undefined (reading 'toolCalls') popup on all llm's.

**Comment by galaridor** [comment]
i have not tested with docker. It works locally with qwen 2.5 coder using ollama for me but i believe you still have to set some env variables inside the dockerfile or docker-compose.yaml files

**Comment by beenycool** [comment]
> will look into this

any update?

**Comment by thecodacus** [comment]
can you try this PR https://github.com/stackblitz-labs/bolt.diy/pull/895
this has couple of bugfixes and improved logging

**Comment by mutlumehmet** [comment]
Getting same error even if I run it on Pinokio
M1 chip Mac, OpenAi,

**Comment by gencohd** [comment]
@mutlumehmet I think the m1 chip is a problem with macbook users.

I'm using an m1 chip mac. 

(hocam çözebildiniz mi bu arada)

**Comment by charlyautomatiza** [comment]
![2025-01-04_12h58_41](https://github.com/user-attachments/assets/5afde106-b83f-4f87-98cb-a0daefd0783c)
Same issue here

**Comment by Geekox31** [comment]
Hello,

Same issue.... any update or solution ?

**Comment by copernix** [comment]
pinokio released 3.2.0 also Bolt released SCRIPT VERSION 3.0. I had the same problem but when I tried the new version the problem seems to have disappeared. 
op:Windows 11

**Comment by thecodacus** [comment]
another observation I found that if you post image and the model does not support vision capability, this issue occurs

**Comment by Datlyfe** [comment]
I don't think it's related to pinokio, i'm getting the same issue running locally, happens when sending prompts with images, regulart text prompts are working fine.
provider: claude sonnet 3.5
system : windows 11 wsl2
bolt version: 0.0.5

**Comment by jaimedevelop** [comment]
Hello: The way to solve this: Remove bolt.diy from "Pinokio" and install it back. Do not unistall Pinokio. Just install back bolt and no more problems. It seems like the installation you have does not have the last navigation routing to the right bolt.diy fork. This happened to me and I follow this simple steps and it worked.

**Comment by thecodacus** [comment]
good news is we have docker image published 
so if anyone wants to directly load from docker without building the app can do so using this image
https://github.com/stackblitz-labs/bolt.diy/pkgs/container/bolt.diy

note: you have to use docker login to login to ghcr.io with your githubaccess token to access the image

**Comment by gencohd** [comment]
> good news is we have docker image published so if anyone wants to directly load from docker without building the app can do so using this image https://github.com/stackblitz-labs/bolt.diy/pkgs/container/bolt.diy
> 
> note: you have to use docker login to login to ghcr.io with your githubaccess token to access the image



error 404 page not found

**Comment by kewlniss** [comment]
I had the issue when using a prompt qwen2.5-coder but not llama3.2. Didn't get it resolved but I wanted to add my experience. This is with the latest dev which includes PR #895. I wasn't able to try with the docker image as it is still private currently.

**Comment by yanoyuh** [comment]
I think it's probably due to the node version.

In my case it was resolved by removing the already installed node_modules, switching the node version and running npm install.

success node version: v20.13.1
failed node version: v20.15.1

It may be not supported version of the module is included.

**Comment by thecodacus** [comment]
docker image is public now
