### ISSUE TITLE
Cannot access to localhost:11434 where ollama is running 

### ISSUE THREAD

**Issue by Soumyaranjan-17** [stackblitz-labs/bolt.diy#874]
### Describe the bug

When I try to run a local ai model in this app
It listed all the available **provider** and all the available **model** 
But it cannot connect to localhost:11434 
May be due to **CORS** Cross-Origin Resource Sharing

### Link to the Bolt URL that caused the error

localhost:5135

### Steps to reproduce

Try to use some local model 

### Expected behavior

it will not connect to localhost:11434
for this the error will arise 
```
Failed to get Ollama models: TypeError: fetch failed
    at node:internal/deps/undici/undici:13484:13
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at OllamaProvider.getDynamicModels (C:/D/BOLT/app/lib/modules/llm/providers/ollama.ts:41:24)
    at async Promise.all (index 0)
    at LLMManager.updateModelList (C:/D/BOLT/app/lib/modules/llm/manager.ts:71:27)
    at Module.getModelList (C:/D/BOLT/app/utils/constants.ts:43:10)
    at Module.streamText (C:/D/BOLT/app/lib/.server/llm/stream-text.ts:99:22)
    at chatAction (C:/D/BOLT/app/routes/api.chat.ts:101:20)
    at Object.callRouteAction (C:\D\BOLT\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\data.js:36:16)
    at C:\D\BOLT\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4899:19
    at callLoaderOrAction (C:\D\BOLT\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4963:16)
    at async Promise.all (index 0)
    at defaultDataStrategy (C:\D\BOLT\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4772:17)
    at callDataStrategyImpl (C:\D\BOLT\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4835:17)
    at callDataStrategy (C:\D\BOLT\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3992:19)
    at submit (C:\D\BOLT\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3755:21) 
    at queryImpl (C:\D\BOLT\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3684:22)
    at Object.queryRoute (C:\D\BOLT\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3629:18)
    at handleResourceRequest (C:\D\BOLT\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:402:20)
    at requestHandler (C:\D\BOLT\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:156:18)
    at C:\D\BOLT\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_3djlhh3t6jbfog2cydlrvgreoy\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:70:25 {
  [cause]: Error: connect ECONNREFUSED ::1:11434
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 11434
  }
}
```

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/3560cd44-d078-40a9-8af0-6625da8e39e0)
![image](https://github.com/user-attachments/assets/81c9d284-69d2-4a14-8c24-a2496b74e62e)
![image](https://github.com/user-attachments/assets/01141696-2284-410c-9e01-4cafe4467aab)
![image](https://github.com/user-attachments/assets/b31a9907-deb0-4f87-9ab9-704037500fe9)

### Platform

- OS: Windows 11
- Browser:  Chrome Canary
- Version: latest 
```
Processor	11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz   3.00 GHz
Installed RAM	8.00 GB (7.67 GB usable)
System type	64-bit operating system, x64-based processor
```

### Provider Used

Ollama 

### Model Used

qwen2.5-coder:3b

### Additional context

Add the support for Cross-Origin Resource Sharing

**Comment by Soumyaranjan-17** [comment]
**SET in .env**
```
OLLAMA_API_BASE_URL=http://127.0.0.1:11434
```

don't set 

> OLLAMA_API_BASE_URL=http://localhost:11434
it is wrong due to some IPV6 problem 

and in UI that input field should be clear otherwise it will override the .env

![image](https://github.com/user-attachments/assets/32d00a23-786d-4a49-95e4-ebf3254f1a66)

**Comment by VictimOfPing** [comment]
> **SET in .env**
> 
> ```
> OLLAMA_API_BASE_URL=http://127.0.0.1:11434
> ```
> 
> don't set
> 
> > OLLAMA_API_BASE_URL=http://localhost:11434
> > it is wrong due to some IPV6 problem
> 
> and in UI that input field should be clear otherwise it will override the .env
> 
> ![image](https://private-user-images.githubusercontent.com/128879861/398006034-32d00a23-786d-4a49-95e4-ebf3254f1a66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MDYzMzMsIm5iZiI6MTczNDkwNjAzMywicGF0aCI6Ii8xMjg4Nzk4NjEvMzk4MDA2MDM0LTMyZDAwYTIzLTc4NmQtNGE0OS05NWU0LWViZjMyNTRmMWE2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMlQyMjIwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTI1ZTBlNDJhYjYxNjQ5Nzc3YjY5Mjk5N2JkOTk5MDc3ZTNkZmE5ODM4YzI5ZjM1ODhkNTdiM2FhZTgxYjc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8AeXXd9r_GdsMw05pY3-DH963kuYbluF-uFcM-XP0_I)

I did it but it still doesn't go
